### ISSUE TITLE
VertexArrayFactory tests fail on Mac Mini

### ISSUE THREAD

**Issue by shunter** [AnalyticalGraphicsInc/cesium#1061]
These have always failed on here, but I noticed we didn't have an issue for it.

Mac OS X Lion 10.7.5
AMD Radeon HD 6630M 256 MB

```
Renderer/VertexArrayFactory sorts interleaved attributes from large to small components. (show summary)
Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 0, length : 4, byteLength : 4, byteOffset : 0, buffer : { byteLength : 4 } } to equal [ 255, 255, 255, 255 ].
Error: Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 0, length : 4, byteLength : 4, byteOffset : 0, buffer : { byteLength : 4 } } to equal [ 255, 255, 255, 255 ].
    at new jasmine.ExpectationResult (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:114:32)
    at null.toEqual (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1243:29)
    at null.<anonymous> (http://localhost:8080/Specs/Renderer/VertexArrayFactorySpec.js:316:38)
    at jasmine.Block.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1072:17)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Spec.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2386:14)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Suite.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2533:14)
    at null.execute (http://localhost:8080/Specs/SpecRunner.js:133:29)


Renderer/VertexArrayFactory sorts interleaved attributes from large to small components (3). (show summary)
Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 0, length : 4, byteLength : 4, byteOffset : 0, buffer : { byteLength : 4 } } to equal [ 255, 255, 255, 255 ].
Error: Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 0, length : 4, byteLength : 4, byteOffset : 0, buffer : { byteLength : 4 } } to equal [ 255, 255, 255, 255 ].
    at new jasmine.ExpectationResult (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:114:32)
    at null.toEqual (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1243:29)
    at null.<anonymous> (http://localhost:8080/Specs/Renderer/VertexArrayFactorySpec.js:449:38)
    at jasmine.Block.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1072:17)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Spec.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2386:14)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Suite.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2533:14)
    at null.execute (http://localhost:8080/Specs/SpecRunner.js:133:29)


Renderer/VertexArrayFactory creates a custom interleaved vertex. (show summary)
Expected { 0 : 75, 1 : 0, 2 : 255, 3 : 255, length : 4, byteLength : 4, byteOffset : 0, buffer : { byteLength : 4 } } to equal [ 255, 0, 0, 255 ].
Error: Expected { 0 : 75, 1 : 0, 2 : 255, 3 : 255, length : 4, byteLength : 4, byteOffset : 0, buffer : { byteLength : 4 } } to equal [ 255, 0, 0, 255 ].
    at new jasmine.ExpectationResult (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:114:32)
    at null.toEqual (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1243:29)
    at null.<anonymous> (http://localhost:8080/Specs/Renderer/VertexArrayFactorySpec.js:523:38)
    at jasmine.Block.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1072:17)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Spec.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2386:14)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2100:18)
    at jasmine.Spec.finish (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2360:5)
    at null.onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2387:10)
Expected { 0 : 100, 1 : 0, 2 : 0, 3 : 255, length : 4, byteLength : 4, byteOffset : 0, buffer : { byteLength : 4 } } to equal [ 0, 255, 0, 255 ].
Error: Expected { 0 : 100, 1 : 0, 2 : 0, 3 : 255, length : 4, byteLength : 4, byteOffset : 0, buffer : { byteLength : 4 } } to equal [ 0, 255, 0, 255 ].
    at new jasmine.ExpectationResult (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:114:32)
    at null.toEqual (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1243:29)
    at null.<anonymous> (http://localhost:8080/Specs/Renderer/VertexArrayFactorySpec.js:551:38)
    at jasmine.Block.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1072:17)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Spec.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2386:14)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2100:18)
    at jasmine.Spec.finish (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2360:5)
    at null.onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2387:10)
```

**Comment by hpinkos** [comment]
@shunter Can you verify that this test failure still happens?

**Comment by shunter** [comment]
I can't.  The Mac Mini is in the Cesium lab now.

**Comment by hpinkos** [comment]
Ah right, thanks.  I'll look at this when we get back in the office

**Comment by pjcozzi** [comment]
I can't reproduce this on my MacBook Pro Intel, but there are other failures I will address separately.

Since no one else has mentioned this in over three years, I think this is insufficient priority to even look into.
