### ISSUE TITLE
sampleTerrain specs don't wait for terrainProvider.isReady

### ISSUE THREAD

**Issue by shunter** [AnalyticalGraphicsInc/cesium#1493]
Noticed because cesiumjs.org is down at the moment, leading to the misleading error:

```
Scene/sampleTerrain queries heights. (show summary)
DeveloperError: getTilingScheme must not be called before the terrain provider is ready.
Error
    at new DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:40:19)
    at CesiumTerrainProvider.getTilingScheme (http://localhost:8080/Source/Scene/CesiumTerrainProvider.js:447:19)
    at sampleTerrain (http://localhost:8080/Source/Scene/sampleTerrain.js:60:44)
    at null.<anonymous> (http://localhost:8080/Specs/Scene/sampleTerrainSpec.js:24:23)
    at jasmine.Block.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1072:17)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Spec.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2386:14)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Suite.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2533:14)
    at null.execute (http://localhost:8080/Specs/SpecRunner.js:140:29)
Scene/sampleTerrain sets height to undefined if terrain data is not available at the position and specified level. (show summary)
DeveloperError: getTilingScheme must not be called before the terrain provider is ready.
Error
    at new DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:40:19)
    at CesiumTerrainProvider.getTilingScheme (http://localhost:8080/Source/Scene/CesiumTerrainProvider.js:447:19)
    at sampleTerrain (http://localhost:8080/Source/Scene/sampleTerrain.js:60:44)
    at null.<anonymous> (http://localhost:8080/Specs/Scene/sampleTerrainSpec.js:48:23)
    at jasmine.Block.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1072:17)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Spec.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2386:14)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Suite.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2533:14)
    at null.execute (http://localhost:8080/Specs/SpecRunner.js:140:29)
Scene/sampleTerrain fills in what it can when given a mix of positions with and without valid tiles. (show summary)
DeveloperError: getTilingScheme must not be called before the terrain provider is ready.
Error
    at new DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:40:19)
    at CesiumTerrainProvider.getTilingScheme (http://localhost:8080/Source/Scene/CesiumTerrainProvider.js:447:19)
    at sampleTerrain (http://localhost:8080/Source/Scene/sampleTerrain.js:60:44)
    at null.<anonymous> (http://localhost:8080/Specs/Scene/sampleTerrainSpec.js:70:23)
    at jasmine.Block.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1072:17)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Spec.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2386:14)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Suite.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2533:14)
    at null.execute (http://localhost:8080/Specs/SpecRunner.js:140:29)
```

**Comment by manujain** [comment]
@kring , can I work on this bug? If yes, can you tell how to go forward?

**Comment by kring** [comment]
@manujain sorry, this issue was fixed long ago by the pull request mentioned above.  It seems I just didn't get the "Fixes #whatever" syntax right so it wasn't closed automatically.  Closing it now.
