### ISSUE TITLE
Test failures on NVIDIA Quadro K2000M/ driver version 9.18.13.3311

### ISSUE THREAD

**Issue by fstoner** [AnalyticalGraphicsInc/cesium#1703]
Failures in both Firefox (29.0) and Chrome (Version 34.0.1847.137 m).

View: 5460 specs summary | 4 failing | 0 skipped
Scene/Model renders animBoxes without animation. (show summary)
Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 255 } not to equal [ 0, 0, 0, 255 ].
Error: Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 255 } not to equal [ 0, 0, 0, 255 ].
    at new jasmine.ExpectationResult (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:114:32)
    at null.toEqual (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1243:29)
    at null.<anonymous> (http://localhost:8080/Specs/Scene/ModelSpec.js:428:44)
    at jasmine.Block.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1072:17)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Spec.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2386:14)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2100:18)
    at jasmine.Spec.finish (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2360:5)
    at null.onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2387:10)
Scene/Model Animates and renders. (show summary)
Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 255 } not to equal [ 0, 0, 0, 255 ].
Error: Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 255 } not to equal [ 0, 0, 0, 255 ].
    at new jasmine.ExpectationResult (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:114:32)
    at null.toEqual (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1243:29)
    at null.<anonymous> (http://localhost:8080/Specs/Scene/ModelSpec.js:780:49)
    at jasmine.Block.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1072:17)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Spec.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2386:14)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2100:18)
    at jasmine.Spec.finish (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2360:5)
    at null.onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2387:10)
Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 255 } not to equal [ 0, 0, 0, 255 ].
Error: Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 255 } not to equal [ 0, 0, 0, 255 ].
    at new jasmine.ExpectationResult (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:114:32)
    at null.toEqual (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1243:29)
    at null.<anonymous> (http://localhost:8080/Specs/Scene/ModelSpec.js:780:49)
    at jasmine.Block.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1072:17)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Spec.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2386:14)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2100:18)
    at jasmine.Spec.finish (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2360:5)
    at null.onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2387:10)
Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 255 } not to equal [ 0, 0, 0, 255 ].
Error: Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 255 } not to equal [ 0, 0, 0, 255 ].
    at new jasmine.ExpectationResult (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:114:32)
    at null.toEqual (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1243:29)
    at null.<anonymous> (http://localhost:8080/Specs/Scene/ModelSpec.js:780:49)
    at jasmine.Block.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1072:17)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Spec.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2386:14)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2100:18)
    at jasmine.Spec.finish (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2360:5)
    at null.onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2387:10)
Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 255 } not to equal [ 0, 0, 0, 255 ].
Error: Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 255 } not to equal [ 0, 0, 0, 255 ].
    at new jasmine.ExpectationResult (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:114:32)
    at null.toEqual (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1243:29)
    at null.<anonymous> (http://localhost:8080/Specs/Scene/ModelSpec.js:780:49)
    at jasmine.Block.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1072:17)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Spec.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2386:14)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2100:18)
    at jasmine.Spec.finish (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2360:5)
    at null.onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2387:10)
Scene/Vector renders along UNIT_Z. (show summary)
Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 255 } not to equal [ 0, 0, 0, 255 ].
Error: Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 255 } not to equal [ 0, 0, 0, 255 ].
    at new jasmine.ExpectationResult (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:114:32)
    at null.toEqual (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1243:29)
    at null.<anonymous> (http://localhost:8080/Specs/Scene/VectorSpec.js:189:44)
    at jasmine.Block.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1072:17)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Spec.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2386:14)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2100:18)
    at jasmine.Spec.finish (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2360:5)
    at null.onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2387:10)
Scene/Vector renders bounding volume. (show summary)
Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 255 } not to equal [ 0, 0, 0, 255 ].
Error: Expected { 0 : 0, 1 : 0, 2 : 0, 3 : 255 } not to equal [ 0, 0, 0, 255 ].
    at new jasmine.ExpectationResult (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:114:32)
    at null.toEqual (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1243:29)
    at null.<anonymous> (http://localhost:8080/Specs/Scene/VectorSpec.js:198:44)
    at jasmine.Block.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:1072:17)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at jasmine.Queue.start (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2057:8)
    at jasmine.Spec.execute (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2386:14)
    at jasmine.Queue.next_ (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2104:31)
    at onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2100:18)
    at jasmine.Spec.finish (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2360:5)
    at null.onComplete (http://localhost:8080/ThirdParty/jasmine-1.3.1/jasmine.js:2387:10)

**Comment by hpinkos** [comment]
@mramato can you see if this is still a problem?

**Comment by mramato** [comment]
We can actually just close this.  I know for certain that at one point all tests past on Nexus 7 after this issue was written.
