### ISSUE TITLE
Exception when canceling morph while flight in progress.

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#2678]
1. Run the [Camera example](http://localhost:8080/Apps/Sandcastle/index.html?src=Camera.html&label=All).
2. Selected `Fly to Location with heading, pitch, and roll`
3. While in flight, switch to 2D or CV mode
4.  Immediately click the canvas to complete the morph.

You'll get the following stack trace:
```
DeveloperError: lookAtTransform is not supported while morphing.
Error
   at DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:43:13)
   at Camera.prototype.lookAtTransform (http://localhost:8080/Source/Scene/Camera.js:1576:13)
   at Sandcastle.reset (Unknown script code:201:5)
   at Anonymous function (Unknown script code:209:5)
   at Event.prototype.raiseEvent (http://localhost:8080/Source/Core/Event.js:146:17)
   at complete2DCallback (http://localhost:8080/Source/Scene/SceneTransitioner.js:681:9)
   at completeMorph (http://localhost:8080/Source/Scene/SceneTransitioner.js:250:17)
   at handleMouseDown (http://localhost:8080/Source/Core/ScreenSpaceEventHandler.js:156:13)
   at handlePointerDown (http://localhost:8080/Source/Core/ScreenSpaceEventHandler.js:598:13)
   at listener (http://localhost:8080/Source/Core/ScreenSpaceEventHandler.js:66:13) (on line 1576 of http://localhost:8080/Source/Scene/Camera.js)
```

**Comment by mramato** [comment]
Turns out this is bug is specific to the camera Sandcastle example, but might be exposing a race condition with the `morphComplete` event in Cesium itself.

**Comment by mramato** [comment]
CC #2683

**Comment by emackey** [comment]
Load the [Sandcastle Camera](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Camera.html&label=Showcases) demo, and switch to Columbus View.  This error appears at the end of the morph.

```
An error occurred while rendering. Rendering has stopped.
DeveloperError: lookAtTransform is not supported while morphing.
Error
    at new DeveloperError (http://cesiumjs.org/Cesium/Source/Core/DeveloperError.js:43:19)
    at Camera.lookAtTransform (http://cesiumjs.org/Cesium/Source/Scene/Camera.js:1576:19)
    at Object.Sandcastle.reset (<anonymous>:201:19)
    at <anonymous>:209:16
    at Event.raiseEvent (http://cesiumjs.org/Cesium/Source/Core/Event.js:146:30)
    at completeColumbusViewCallback (http://cesiumjs.org/Cesium/Source/Scene/SceneTransitioner.js:706:43)
    at Object.options.complete (http://cesiumjs.org/Cesium/Source/Scene/SceneTransitioner.js:598:17)
    at update (http://cesiumjs.org/Cesium/Source/ThirdParty/Tween.js:403:45)
    at TweenCollection.update (http://cesiumjs.org/Cesium/Source/Scene/TweenCollection.js:539:29)
    at Scene.initializeFrame (http://cesiumjs.org/Cesium/Source/Scene/Scene.js:1373:22)
```

**Comment by zoiclabs** [comment]
+1. The steps provided in #2683 are more accurate. Just switching breaks the app.
