### ISSUE TITLE
Can't switch to CV in Camera Demo

### ISSUE THREAD

**Issue by emackey** [AnalyticalGraphicsInc/cesium#2683]
Load the [Sandcastle Camera](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Camera.html&label=Showcases) demo, and switch to Columbus View.  This error appears at the end of the morph.

```
An error occurred while rendering. Rendering has stopped.
DeveloperError: lookAtTransform is not supported while morphing.
Error
    at new DeveloperError (http://cesiumjs.org/Cesium/Source/Core/DeveloperError.js:43:19)
    at Camera.lookAtTransform (http://cesiumjs.org/Cesium/Source/Scene/Camera.js:1576:19)
    at Object.Sandcastle.reset (<anonymous>:201:19)
    at <anonymous>:209:16
    at Event.raiseEvent (http://cesiumjs.org/Cesium/Source/Core/Event.js:146:30)
    at completeColumbusViewCallback (http://cesiumjs.org/Cesium/Source/Scene/SceneTransitioner.js:706:43)
    at Object.options.complete (http://cesiumjs.org/Cesium/Source/Scene/SceneTransitioner.js:598:17)
    at update (http://cesiumjs.org/Cesium/Source/ThirdParty/Tween.js:403:45)
    at TweenCollection.update (http://cesiumjs.org/Cesium/Source/Scene/TweenCollection.js:539:29)
    at Scene.initializeFrame (http://cesiumjs.org/Cesium/Source/Scene/Scene.js:1373:22)
```

**Comment by emackey** [comment]
Oops, didn't notice #2678.  Still these reproduction steps are even shorter than those.
