### ISSUE TITLE
RangeError: Invalid array buffer length

### ISSUE THREAD

**Issue by icholy** [AnalyticalGraphicsInc/cesium#2853]
I'm getting the following errors sporadically.

```
An error occurred while rendering.  Rendering has stopped.
undefined
RangeError: Invalid array buffer length
RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Float64Array (native)
    at Object.i.createTypedArray (http://192.168.0.36/cop/client/vendor/Cesium/Build/Cesium/Workers/combineGeometry.js:60:1373)
    at z (http://192.168.0.36/cop/client/vendor/Cesium/Build/Cesium/Workers/combineGeometry.js:60:26508)
    at D (http://192.168.0.36/cop/client/vendor/Cesium/Build/Cesium/Workers/combineGeometry.js:60:26673)
    at Object.tt.combineInstances (http://192.168.0.36/cop/client/vendor/Cesium/Build/Cesium/Workers/combineGeometry.js:61:9474)
    at w (http://192.168.0.36/cop/client/vendor/Cesium/Build/Cesium/Workers/combineGeometry.js:61:17483)
    at Object.B.combineGeometry (http://192.168.0.36/cop/client/vendor/Cesium/Build/Cesium/Workers/combineGeometry.js:61:23303)
    at r (http://192.168.0.36/cop/client/vendor/Cesium/Build/Cesium/Workers/combineGeometry.js:61:28230)
    at DedicatedWorkerGlobalScope.<anonymous> (http://192.168.0.36/cop/client/vendor/Cesium/Build/Cesium/Workers/combineGeometry.js:61:27703)P.showErrorPanel @ Cesium.js:465
```

```
Cesium.js:465 An error occurred while rendering.  Rendering has stopped.
undefined
RangeError: Invalid array buffer length
RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Float64Array (native)
    at Object.B.packCreateGeometryResults (http://192.168.0.36/cop/client/vendor/Cesium/Build/Cesium/Workers/createGeometry.js:76:23700)
    at a (http://192.168.0.36/cop/client/vendor/Cesium/Build/Cesium/Workers/createGeometry.js:76:31774)
    at DedicatedWorkerGlobalScope.<anonymous> (http://192.168.0.36/cop/client/vendor/Cesium/Build/Cesium/Workers/createGeometry.js:76:30955)
```

**Comment by mramato** [comment]
This issue usually indicates a bug in user code.  It's almost always caused by a `NaN` or `undefined` value being passed into Cesium.  I recommend you develop against the unminified Cesium.js, which has enhanced error checking and is more likely to catch bad data.  Only use the minified Ceisum.js for deployment.

In the future, please use [the forum](https://groups.google.com/forum/?fromgroups#!forum/cesium-dev) for questions and support.  We try to only write GitHub issues for reproducible bugs.
