### ISSUE TITLE
Label test failure in master

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#3198]
This is in Chrome on my home Windows machine.  I haven't tested any other systems.
```
Scene/LabelCollection can render after adding a label
Expected 11 to be less than 10.
Error: Expected 11 to be less than 10.
    at stack (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1475:17)
    at buildExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1445:14)
    at Spec.Env.expectationResultFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:584:18)
    at Spec.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:332:34)
    at Expectation.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:528:21)
    at Expectation.toBeLessThan (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1399:12)
    at http://localhost:8080/Specs/Scene/LabelCollectionSpec.js:359:27
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:139:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
Expected 11 to be less than 10.
Error: Expected 11 to be less than 10.
    at stack (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1475:17)
    at buildExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1445:14)
    at Spec.Env.expectationResultFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:584:18)
    at Spec.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:332:34)
    at Expectation.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:528:21)
    at Expectation.toBeLessThan (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1399:12)
    at http://localhost:8080/Specs/Scene/LabelCollectionSpec.js:360:27
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:139:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
```

**Comment by pjcozzi** [comment]
This passes on my work Windows laptop.  Will try to reproduce on my home laptop.

**Comment by mramato** [comment]
I still get this all of the time in Chrome on my Windows 10 laptop (Intel HD 4000).

**Comment by mramato** [comment]
It also happens under my nvidia card on the same machine.

**Comment by AmayAgrawal** [comment]
Sir can you please elobrate what type of error is this and when you encounter this error??

**Comment by pjcozzi** [comment]
@AmayAgrawal I don't think this is a good beginner issue.

**Comment by emackey** [comment]
So, what's happening here is we're expecting the Red channel to be bright, and the Green and Blue channels to both be dark (we asked for zero, and we expect less than 10 / 255 as a result).  Some machines use color profiles to tweak rendered colors to look nicer on the particular type of monitor attached, and sometimes this affects our render test results, hence the sloppy expectation.

In this case, the failed rendered result got 11 / 255 when we expected less than 10, but only on some machines.  I would say this is OK -- perhaps a rather extreme color correction, but not out of the realm of the expected.  We could increase the tests to expect less than 20, as opposed to less than 10.

Note that some of these tests look for brightness by expecting "more than 10".  Really these should probably be moved up to expect more than 210.  I wouldn't expect that to break unless we got aggressive and expected more than 245.

**Comment by pjcozzi** [comment]
@bagnell please close this if #4379 fixed it.
