### ISSUE TITLE
 Uncaught DeveloperError thown

### ISSUE THREAD

**Issue by bmckilligan** [AnalyticalGraphicsInc/cesium#3894]
The following error is getting thrown on screen movements.   This was present in 1.20, and is still in 1.21.

Reverting to cesium 1.19 doesn't thrown the error.

the following is the console output in google chrome, Version 50.0.2661.94 m (64-bit) Windows 7 64 bit.  

Cesium.js:24158 Uncaught DeveloperError: This object was destroyed, i.e., destroy() was called.
Error
    at new DeveloperError (http://localhost/cds/Scripts/_Libs/cesium/1.21/Cesium.js:1321:19)
    at VertexArray.throwOnDestroyed (http://localhost/cds/Scripts/_Libs/cesium/1.21/Cesium.js:24158:19)
    at continueDraw (http://localhost/cds/Scripts/_Libs/cesium/1.21/Cesium.js:126700:12)
    at Context.draw (http://localhost/cds/Scripts/_Libs/cesium/1.21/Cesium.js:126737:9)
    at DrawCommand.execute (http://localhost/cds/Scripts/_Libs/cesium/1.21/Cesium.js:63127:17)
    at executeCommand (http://localhost/cds/Scripts/_Libs/cesium/1.21/Cesium.js:155472:21)
    at executeCommands (http://localhost/cds/Scripts/_Libs/cesium/1.21/Cesium.js:155699:17)
    at executeCommandsInViewport (http://localhost/cds/Scripts/_Libs/cesium/1.21/Cesium.js:155949:9)
    at updateAndExecuteCommands (http://localhost/cds/Scripts/_Libs/cesium/1.21/Cesium.js:155840:17)
    at Scene.pick (http://localhost/cds/Scripts/_Libs/cesium/1.21/Cesium.js:156357:9)throwOnDestroyed @ Cesium.js:24158continueDraw @ Cesium.js:126700Context.draw @ Cesium.js:126737DrawCommand.execute @ Cesium.js:63127executeCommand @ Cesium.js:155472executeCommands @ Cesium.js:155699executeCommandsInViewport @ Cesium.js:155949updateAndExecuteCommands @ Cesium.js:155840Scene.pick @ Cesium.js:156357(anonymous function) @ cesium.js:334handleMouseMove @ Cesium.js:56624listener @ Cesium.js:56449

**Comment by hpinkos** [comment]
Hello @bmckilligan,

Have you tried clearing your cache?  Sometimes that can cause weird side effects in chrome when switching between versions.

Otherwise, do you have a code example that causes this to happen?  We haven't seen this on our end.

Thanks!

**Comment by mramato** [comment]
Are you using terrain and/or picking?  I believe this may be a dupe or related to #3779 (which we should fix ASAP)

**Comment by bmckilligan** [comment]
http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=f1bf37574ba19d084c372b5a6d09466f

I was able to replicate the error in a simple example.  I am using the draw helper plugin (http://cesiumjs.org/plugins)  and it was throwing the error on event listeners.  

I have modified the plugin for my own purposes to work with recent versions of cesium and to draw on 3d terrain, but the bug is being thrown in an event listener

If the user zooms in and moves around the globe to where the billboard goes off screen, the error is thrown

**Comment by bagnell** [comment]
@bmckilligan This was fixed in #3779 and will be in the next release.
