### ISSUE TITLE
Primitive test failure only in built release version

### ISSUE THREAD

**Issue by tfili** [AnalyticalGraphicsInc/cesium#3948]
I get the following failure when running all the tests with `?built=true&release=true` on `Chrome 50.0.2661.102 m (64-bit)`

```
Scene/Primitive updates model matrix for one instance in 3D
Expected 3 to equal 1.
Error: Expected 3 to equal 1.
    at stack (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1475:17)
    at buildExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1445:14)
    at Spec.Env.expectationResultFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:584:18)
    at Spec.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:332:34)
    at Expectation.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:528:21)
    at Expectation.toEqual (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1399:12)
    at http://localhost:8080/Specs/Scene/PrimitiveSpec.js:455:33
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:139:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
```

If I run the test by itself (the built release version) I get a different failure

```
Scene/Primitive updates model matrix for one instance in 3D
Expected 0 to equal 1.
Error: Expected 0 to equal 1.
    at stack (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1475:17)
    at buildExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1445:14)
    at Spec.Env.expectationResultFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:584:18)
    at Spec.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:332:34)
    at Expectation.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:528:21)
    at Expectation.toEqual (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1399:12)
    at http://localhost:8080/Specs/Scene/PrimitiveSpec.js:455:33
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:139:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
TypeError: Cannot read property 'modelMatrix' of undefined
TypeError: Cannot read property 'modelMatrix' of undefined
    at http://localhost:8080/Specs/Scene/PrimitiveSpec.js:456:27
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:139:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
    at QueueRunner.execute (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1732:10)
    at Spec.Env.queueRunnerFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:620:35)
    at Spec.execute (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:357:10)
    at Object.fn (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:2095:43)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
```

**Comment by pjcozzi** [comment]
@tfili is this also in 1.21?

**Comment by tfili** [comment]
@pjcozzi Yep, this is also failing in 1.21.

**Comment by pjcozzi** [comment]
OK, will keep it labeled just `1.21`.

**Comment by pjcozzi** [comment]
OK, will keep it labeled just `test failure`.

**Comment by pjcozzi** [comment]
Still failing in 1.23.  @lilleyse can you look at this by the 1.24 release?

This test returns three commands in release (but only one in "debug" as expected).

![image](https://cloud.githubusercontent.com/assets/782098/16520874/26dc94d0-3f61-11e6-8e3a-4ae2aeb53a8c.png)

**Comment by pjcozzi** [comment]
Leave labeled `next release`, but push for 1.24.

**Comment by pjcozzi** [comment]
@lilleyse up to you if you want to investigate or push past 1.25.

**Comment by mramato** [comment]
During today's release testing, I still get `Scene/Primitive updates model matrix for one instance in 3D` in all browsers when running against the combined file with debug code removed.

**Comment by shehzan10** [comment]
* As of 1.27-1.29, the only failure is `Scene/Primitive can mix valid and invalid geometry`.
* **As of v1.30, there are no failures.**

Tested on Chrome (Stable + Canary), Edge, Firefox using `npm run minifyRelease && cd Build && npm start` and then running `http://localhost:8080/Specs/SpecRunner.html?spec=Scene%2FPrimitive`.

**Comment by pjcozzi** [comment]
Thanks @shehzan10, I can confirm these are no longer an issue with `?built=true&release=true`.
