### ISSUE TITLE
Toggling map visibility causes crash

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4083]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/11JV-fgCW2s

The user says it seems to have been introduced in 1.20

Run this code and zoom in and out.  The crash usually happens within a few toggles.  There are also might be a z-ordering issues with the imagery layers after show has been toggled.  It looks like the argcis tiles will randomly show above the black marble ones.

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer', {
    imageryProvider : new Cesium.ArcGisMapServerImageryProvider({
        url : 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer'
    }),
    baseLayerPicker : false
});

var layers = viewer.imageryLayers;
var blackMarble = layers.addImageryProvider(Cesium.createTileMapServiceImageryProvider({
    url : 'https://cesiumjs.org/blackmarble',
    credit : 'Black Marble imagery courtesy NASA Earth Observatory',
    flipXY : true // Only old gdal2tile.py generated tilesets need this flag.
}));

setInterval( function() {
    blackMarble.show = !blackMarble.show;
}, 2000 );
```

**Comment by hpinkos** [comment]
It crashes from calling `destroy` on `imagery.texture`

```
DeveloperError: This object was destroyed, i.e., destroy() was called.
Error
    at new DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:44:19)
    at Texture.throwOnDestroyed (http://localhost:8080/Source/Core/destroyObject.js:45:19)
    at ComputeCommand.postExecute (http://localhost:8080/Source/Scene/ImageryLayer.js:773:33)
    at ComputeEngine.execute (http://localhost:8080/Source/Renderer/ComputeEngine.js:145:28)
    at ComputeCommand.execute (http://localhost:8080/Source/Renderer/ComputeCommand.js:116:23)
    at executeComputeCommands (http://localhost:8080/Source/Scene/Scene.js:1808:28)
    at executeCommandsInViewport (http://localhost:8080/Source/Scene/Scene.js:2102:13)
    at updateAndExecuteCommands (http://localhost:8080/Source/Scene/Scene.js:1965:17)
    at render (http://localhost:8080/Source/Scene/Scene.js:2370:9)
    at Scene.render (http://localhost:8080/Source/Scene/Scene.js:2408:13)
```

**Comment by keann** [comment]
Yep, faced the same problem. To be precise, problem appears at enabling a layer in case previously it was enabled and then disabled immediately, before complete render, like at the moment on screenshot. For me it's like half a sec, and for TS from gg even 2 seconds were enough to get an error.

![2016-07-06 13 59 50](https://cloud.githubusercontent.com/assets/12268898/16615922/7daab92a-4382-11e6-9af3-c9cb1d29b89d.png)
