### ISSUE TITLE
ie11 problem

### ISSUE THREAD

**Issue by lucasvw** [AnalyticalGraphicsInc/cesium#4091]
Hi guys,

We just encountered an ie11 problem. Cesium throws an error upon using 

viewer.scene.pickPosition()

TypeError: Object doesn't support property or method 'fill'
TypeError: Object doesn't support property or method 'fill'
   at T (http://localhost/vcm/lib/thirdparty/Cesium/Cesium.js:459:30490)
   at S.prototype.setColor (http://localhost/vcm/lib/thirdparty/Cesium/Cesium.js:460:1172)
   at color.set (http://localhost/vcm/lib/thirdparty/Cesium/Cesium.js:459:28961)
   at Anonymous function (http://localhost/vcm/src/vcs/vcm/layer/cesium/buildingsLayer.js:185:25)
   at Anonymous function (http://localhost/vcm/src/vcs/vcm/layer/cesium/buildingsLayer.js:168:21)
   at vcs.vcm.layer.cesium.Buildings.prototype.applyStyle (http://localhost/vcm/src/vcs/vcm/layer/cesium/buildingsLayer.js:157:13)
   at i.prototype.raiseEvent (http://localhost/vcm/lib/thirdparty/Cesium/Cesium.js:423:24310)
   at U (http://localhost/vcm/lib/thirdparty/Cesium/Cesium.js:463:13524)
   at T.prototype.update (http://localhost/vcm/lib/thirdparty/Cesium/Cesium.js:463:16244)
   at a.prototype.update (http://localhost/vcm/lib/thirdparty/Cesium/Cesium.js:470:4541)

We could trace it back to the following commit: https://github.com/AnalyticalGraphicsInc/cesium/commit/24c199c9d08cb6369362ba3c5298989610e95947

Would you consider reverting this commit?

Best,
Lucas

**Comment by mramato** [comment]
Thanks @lucasvw, this is a known issue that is discussed in #3614.  The 3D-Tiles branch is in development and this will get fixed before it is officially released (but I don't have a specific time frame for you yet).

@lilleyse perhaps someone can look at this soon?

**Comment by lucasvw** [comment]
wow, that was a fast reply :)
Thanks!

**Comment by lilleyse** [comment]
@lilleyse perhaps someone can look at this soon?

Yup I'll take a look soon.
