### ISSUE TITLE
Race condition in rendering engine when using KML NetworkLink

### ISSUE THREAD

**Issue by wulfgarpro** [AnalyticalGraphicsInc/cesium#4421]
_Ubuntu 16.04.1 LTS (Xenial Xerus)
Google Chrome Version 53.0.2785.143 (64-bit)
Cesium v1.26_

I've been contending with a issue rendering KML in Cesium using NetworkLink refresh intervals of 0.5 seconds.  

Here is the stack trace:
_An error occurred while rendering.  Rendering has stopped.
undefined
DeveloperError: point is required.
Error
    at new DeveloperError (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:1317:19)
    at Function.BoundingSphere.expand (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:13377:19)
    at writePositionScaleAndRotation (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:76343:28)
    at writeBillboard (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:76717:9)
    at BillboardCollection.update (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:76880:21)
    at LabelCollection.update (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:104614:29)
    at PrimitiveCollection.update (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:155007:27)
    at updatePrimitives (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:163259:27)
    at executeCommandsInViewport (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:163175:9)
    at updateAndExecuteCommands (http://localhost:8080/cesium/Build/CesiumUnminified/Cesium.js:163043:17)_

Here is a screen shot of the issue:
![screenshot from 2016-10-12 13-23-51](https://cloud.githubusercontent.com/assets/955316/19295338/abd49506-907f-11e6-99a1-908f1df21167.png)

The problem seems to be a race condition between the rendering engine, it's handling of the current entity state on the webgl scene, and the rate at which KML entities are added/removed (I'm generating this using an in-house tool on the side) using KML's NetworkLink ability.  To reproduce the issue I generate a KML representation of multiple entities with unique IDs, then alter the incoming KML programmatically with different entities with different IDs, causing Cesium to throw the exception in the above log.

My current work around is the following patch: 
[patch.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/523530/patch.txt)

**Comment by mramato** [comment]
Thanks for the report @wulfgarpro.  I think your workaround is probably masking a larger issue.  There are some other race-condition oriented crashes in KML billboards that have been introduced in the last couple of versions that we plan on tackling this week.  Once those fixes are in, I'll let you know so you can try them out and report back.  Thanks.

**Comment by wulfgarpro** [comment]
Thanks Matt, understood.  I'd rather not implement larger architectural
fixes; undoubtedly my inexperience with the project would introduce more
harm than good.

Looking forward to hearing back.

**Comment by wulfgarpro** [comment]
Hi @mramato,

Any traction on these problems?
