### ISSUE TITLE
Unexpected error message in cesium 1.26 anfter adding cylinder entity

### ISSUE THREAD

**Issue by bmckilligan** [AnalyticalGraphicsInc/cesium#4428]
This is occurring  after adding an entity with a cylinder geometry.

this was introduced in cesium 1.26

I have tested it with version 1.23, 1.24, 1.25 without issue.

I am trying to recreate the error in a Sandcastle example, but have been unsuccessful so far

Cesium.js:175233 An error occurred while rendering.  Rendering has stopped.
undefined
TypeError: Cannot read property 'longitude' of undefined
TypeError: Cannot read property 'longitude' of undefined
    at GeographicProjection.project (http://localhost/cds/Scripts/_Libs/cesium/1.26/Cesium.js:5684:29)
    at updateBatchTableBoundingSpheres (http://localhost/cds/Scripts/_Libs/cesium/1.26/Cesium.js:93503:39)
    at Primitive.update (http://localhost/cds/Scripts/_Libs/cesium/1.26/Cesium.js:93890:13)
    at PrimitiveCollection.update (http://localhost/cds/Scripts/_Libs/cesium/1.26/Cesium.js:157993:27)
    at updatePrimitives (http://localhost/cds/Scripts/_Libs/cesium/1.26/Cesium.js:166212:27)
    at executeCommandsInViewport (http://localhost/cds/Scripts/_Libs/cesium/1.26/Cesium.js:166122:9)
    at updateAndExecuteCommands (http://localhost/cds/Scripts/_Libs/cesium/1.26/Cesium.js:165990:17)
    at render (http://localhost/cds/Scripts/_Libs/cesium/1.26/Cesium.js:166420:9)
    at Scene.render (http://localhost/cds/Scripts/_Libs/cesium/1.26/Cesium.js:166458:13)
    at CesiumWidget.render (http://localhost/cds/Scripts/_Libs/cesium/1.26/Cesium.js:175280:25)

**Comment by mramato** [comment]
If it crashes in your app but not in Sandcastle then the cylinder may not be the real problem.  Have you tried running your app in incognito mode?  Does it happen in all browsers?  Unfortunately there's not much we can do without a reproducible test case.

**Comment by bmckilligan** [comment]
totally understandable, for the moment I rolled back to 1.25 until I can isolate the problem, 

cesium stops rendering and displays the message until I run code to remove the entity , after this it snaps back to life

**Comment by bmckilligan** [comment]
I have isolated the bug, 

it occurs when the viewer is initiated with scene3DOnly: true 

http://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=de5672557b9ff6ee9f5bfa9a3564e49b

**Comment by hpinkos** [comment]
Thanks for looking into this @bmckilligan!  I've labeled this for the bug bash, hopefully it's an easy fix and we can get it resolved soon

**Comment by pjcozzi** [comment]
@bmckilligan thanks again for the report.  This was fixed in #4461 and will be in Cesium 1.27 on Nov 1.

@mramato @hpinkos will test #3523 now.
