### ISSUE TITLE
Scene/LabelCollection computes bounding sphere in Columbus view

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4566]
`Scene/LabelCollection computes bounding sphere in Columbus view` occasionally fails for me in Chrome (and possible other browsers)

```javascript
Scene/LabelCollection computes bounding sphere in Columbus view
Expected 5565974.539663677 to be greater than 5565974.539663677.
Error: Expected 5565974.539663677 to be greater than 5565974.539663677.
    at stack (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1475:17)
    at buildExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1445:14)
    at Spec.expectationResultFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:584:18)
    at Spec.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:332:34)
    at Expectation.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:528:21)
    at Expectation.toBeGreaterThan (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1399:12)
    at http://localhost:8080/Specs/Scene/LabelCollectionSpec.js:1664:31
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:139:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
```

**Comment by pjcozzi** [comment]
Might just need an epsilon/`>=`
