### ISSUE TITLE
Crash when switching scene modes during flight

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#4570]
Found during release testing, but confirmed to happen as far back as 1.25 so I don't think it needs to hold it up.  We should fix it for 1.28 however.

1. Run Cesium Viewer and switch to 2D
2. Zoom in anywhere.
3. Press the home button and switch to 3D during the flight.
4.  Click anywhere to immediately finish the morph.
5. Crash

```
TypeError: Unable to get property 'height' of undefined or null reference
TypeError: Unable to get property 'height' of undefined or null reference
   at Camera.prototype._updateCameraChanged (http://localhost:8080/Source/Scene/Camera.js:333:9)
   at Scene.prototype.initializeFrame (http://localhost:8080/Source/Scene/Scene.js:2338:9)
   at CesiumWidget.prototype.render (http://localhost:8080/Source/Widgets/CesiumWidget/CesiumWidget.js:680:13)
   at render (http://localhost:8080/Source/Widgets/CesiumWidget/CesiumWidget.js:72:25)
```

**Comment by hpinkos** [comment]
Duplicate #1596?

**Comment by mramato** [comment]
I don't think so.  They may be related but this is a crash, not just stuff disappearing during the morph.

**Comment by tfili** [comment]
@mramato who needs to look at this? Is it @bagnell?

**Comment by pjcozzi** [comment]
Pushing to 1.29 to not hold up the release.

**Comment by pjcozzi** [comment]
Removing `next release` label since this is not as critical as others.  Will relabel when I triage soon.
