### ISSUE TITLE
Test failures when no WebGL extensions are supported

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#4711]
In Context.js, change the [getExtension](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Renderer/Context.js#L160) function to just `return undefined;`.  I get 9 new test failures:

```
Renderer/VertexArray renders with a one-component constant value
Expected [ 0, 0, 0, 0 ] to equal [ 255, 255, 255, 255 ].
Error: Expected [ 0, 0, 0, 0 ] to equal [ 255, 255, 255, 255 ].
    at stack (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1475:17)
    at buildExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1445:14)
    at Spec.expectationResultFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:584:18)
    at Spec.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:332:34)
    at Expectation.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:528:21)
    at Expectation.toEqual (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1399:12)
    at http://localhost:8080/Specs/Renderer/VertexArraySpec.js:273:38
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:139:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
Renderer/VertexArray renders with a four-component constant value
Expected [ 0, 0, 0, 0 ] to equal [ 255, 255, 255, 255 ].
Error: Expected [ 0, 0, 0, 0 ] to equal [ 255, 255, 255, 255 ].
    at stack (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1475:17)
    at buildExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1445:14)
    at Spec.expectationResultFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:584:18)
    at Spec.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:332:34)
    at Expectation.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:528:21)
    at Expectation.toEqual (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1399:12)
    at http://localhost:8080/Specs/Renderer/VertexArraySpec.js:426:38
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:139:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
DataSources/CorridorGeometryUpdater A time-varying color causes ground geometry to be dynamic
Expected false to be true.
Error: Expected false to be true.
    at stack (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1475:17)
    at buildExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1445:14)
    at Spec.expectationResultFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:584:18)
    at Spec.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:332:34)
    at Expectation.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:528:21)
    at Expectation.toBe (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1399:12)
    at http://localhost:8080/Specs/DataSources/CorridorGeometryUpdaterSpec.js:251:35
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:139:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
DataSources/EllipseGeometryUpdater A time-varying color causes ground geometry to be dynamic
Expected false to be true.
Error: Expected false to be true.
    at stack (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1475:17)
    at buildExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1445:14)
    at Spec.expectationResultFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:584:18)
    at Spec.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:332:34)
    at Expectation.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:528:21)
    at Expectation.toBe (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1399:12)
    at http://localhost:8080/Specs/DataSources/EllipseGeometryUpdaterSpec.js:277:35
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:139:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
DataSources/PolygonGeometryUpdater A time-varying color causes ground geometry to be dynamic
Expected false to be true.
Error: Expected false to be true.
    at stack (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1475:17)
    at buildExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1445:14)
    at Spec.expectationResultFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:584:18)
    at Spec.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:332:34)
    at Expectation.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:528:21)
    at Expectation.toBe (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1399:12)
    at http://localhost:8080/Specs/DataSources/PolygonGeometryUpdaterSpec.js:262:35
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:139:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
DataSources/RectangleGeometryUpdater A time-varying color causes ground geometry to be dynamic
Expected false to be true.
Error: Expected false to be true.
    at stack (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1475:17)
    at buildExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1445:14)
    at Spec.expectationResultFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:584:18)
    at Spec.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:332:34)
    at Expectation.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:528:21)
    at Expectation.toBe (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1399:12)
    at http://localhost:8080/Specs/DataSources/RectangleGeometryUpdaterSpec.js:248:35
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:139:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
Scene/BillboardCollection renders more than 16K billboards
Expected [ 0, 0, 0, 255 ] to equal [ 255, 255, 255, 255 ].
Error: Expected [ 0, 0, 0, 255 ] to equal [ 255, 255, 255, 255 ].
    at stack (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1475:17)
    at buildExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1445:14)
    at Spec.expectationResultFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:584:18)
    at Spec.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:332:34)
    at Expectation.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:528:21)
    at Expectation.toEqual (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1399:12)
    at http://localhost:8080/Specs/Scene/BillboardCollectionSpec.js:909:40
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:139:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
Scene/GroundPrimitive renders with distance display condition per instance attribute
DeveloperError: must call update before calling getGeometryInstanceAttributes
Error
    at new DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:44:19)
    at GroundPrimitive.getGeometryInstanceAttributes (http://localhost:8080/Source/Scene/GroundPrimitive.js:1195:19)
    at http://localhost:8080/Specs/Scene/GroundPrimitiveSpec.js:543:40
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:139:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
    at QueueRunner.execute (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1732:10)
    at Spec.queueRunnerFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:620:35)
    at Spec.execute (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:357:10)
    at Object.fn (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:2095:43)
Scene/Material draws PolylineArrow built-in material
RuntimeError: Fragment shader failed to compile.  Compile log: WARNING: 0:? : '
' : extension directive should occur before any non-preprocessor tokens 
WARNING: 0:? : 'GL_OES_standard_derivatives' : extension is not supported
ERROR: 0:18: 'fwidth' : no matching overloaded function found 

Error
    at new RuntimeError (http://localhost:8080/Source/Core/RuntimeError.js:43:19)
    at createAndLinkProgram (http://localhost:8080/Source/Renderer/ShaderProgram.js:233:23)
    at initialize (http://localhost:8080/Source/Renderer/ShaderProgram.js:454:23)
    at ShaderProgram._bind (http://localhost:8080/Source/Renderer/ShaderProgram.js:471:9)
    at beginDraw (http://localhost:8080/Source/Renderer/Context.js:1075:12)
    at Context.draw (http://localhost:8080/Source/Renderer/Context.js:1153:9)
    at DrawCommand.execute (http://localhost:8080/Source/Renderer/DrawCommand.js:484:17)
    at executeCommand (http://localhost:8080/Source/Scene/Scene.js:1498:21)
    at executeTranslucentCommandsSorted (http://localhost:8080/Source/Scene/Scene.js:1598:13)
    at executeCommands (http://localhost:8080/Source/Scene/Scene.js:1787:13)
```

**Comment by pjcozzi** [comment]
On Windows/Chrome (didn't test elsewhere), I now only get this one new test failure when extensions are disabled as described above

> Scene/Primitive renders in Columbus view when scene3DOnly is false
Expected to render [0,0,0,255], but actually rendered [165,165,0,255].
Error: Expected to render [0,0,0,255], but actually rendered [165,165,0,255].
    at stack (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1475:17)
    at buildExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1445:14)
    at Spec.expectationResultFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:584:18)
    at Spec.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:332:34)
    at Expectation.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:528:21)
    at Expectation.toRender (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1399:12)
    at verifyPrimitiveRender (http://localhost:8080/Specs/Scene/PrimitiveSpec.js:345:23)
    at http://localhost:8080/Specs/Scene/PrimitiveSpec.js:360:9
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:139:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)

**Comment by shehzan10** [comment]
> Scene/Primitive renders in Columbus view when scene3DOnly is false

Interesting. I re-ran the tests on Chrome and Firefox on Windows but I don't see that test (all tests pass). Can you provide any more info (Chrome version maybe)?

**Comment by pjcozzi** [comment]
Same Chrome and Firefox versions.

It passes when ran alone: http://localhost:8080/Specs/SpecRunner.html?spec=Scene%2FPrimitive%20renders%20in%20Columbus%20view%20when%20scene3DOnly%20is%20false

But fails when all the `Primitive` tests are ran: http://localhost:8080/Specs/SpecRunner.html?spec=Scene%2FPrimitive
