### ISSUE TITLE
readyImagery is not actually ready

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#4777]
Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/Q2qkuxWVj4s

There's a crash in `GlobeSurfaceTileProvider` when you zoom into some of the tiles: 

> it happens when zoomed between tiles with X coordinates 2047, 0 and any of the poles, as well as the opposite side of the globe - between tiles 1023, 1024 and any of the poles (places where one side is loaded and other is still blurry and loading)

It only happens the first time the tiles are loaded in, not after they are cached.  I can reproduce it by opening a new incognito window and zooming in and out on the top row of numbers near the north pole.

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer', {
    baseLayerPicker : true
});

var layers = viewer.imageryLayers;
var coordinateTiles = layers.addImageryProvider(Cesium.createOpenStreetMapImageryProvider({
    url : 'http://commercialplanet.eu/cesium/data6/coordinatestiles',
    maximumLevel : 11,
    credit : ''
})); 
```

```
    at new DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:44:19)
    at addDrawCommandsForTile (http://localhost:8080/Source/Scene/GlobeSurfaceTileProvider.js:1097:27)
    at GlobeSurfaceTileProvider.endUpdate (http://localhost:8080/Source/Scene/GlobeSurfaceTileProvider.js:396:17)
    at QuadtreePrimitive.update (http://localhost:8080/Source/Scene/QuadtreePrimitive.js:306:32)
    at Globe.update (http://localhost:8080/Source/Scene/Globe.js:516:21)
    at updatePrimitives (http://localhost:8080/Source/Scene/Scene.js:2201:26)
    at executeCommandsInViewport (http://localhost:8080/Source/Scene/Scene.js:2106:9)
    at updateAndExecuteCommands (http://localhost:8080/Source/Scene/Scene.js:1974:17)
    at render (http://localhost:8080/Source/Scene/Scene.js:2404:9)
    at Scene.render (http://localhost:8080/Source/Scene/Scene.js:2442:13)
```

**Comment by hpinkos** [comment]
@kring this sounds related to your fix in #4763.  Any ideas?

**Comment by pjcozzi** [comment]
Was this fixed in 1.29?

From CHANGES.md:

> Fixed a bug that could cause a "readyImagery is not actually ready" exception with some configurations of imagery layers.

**Comment by hpinkos** [comment]
@pjcozzi I was able to reproduce this in master after that was merged

**Comment by svetoslav80** [comment]
Yeah I just tested with 1.29 too, it's still not fixed
