### ISSUE TITLE
branch 3d-tiles npm install fails

### ISSUE THREAD

**Issue by jdambruch** [AnalyticalGraphicsInc/cesium#5126]
Hi,
after checking out latest branch 3d-tiles the npm install fails on mac. Build on linux also fails but for different reasons...

Error: Cannot find module 'ajv'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jdambruc/projects/smarticipate/cesium-ref/node_modules/request/node_modules/har-validator/lib/node4/promise.js:30:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
npm WARN prefer global jshint@2.9.4 should be installed with -g

[npm-debug.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/855088/npm-debug.txt)

**Comment by mramato** [comment]
You are using node `v0.12.4`, building and developing Cesium requires `v4.x` or later.  Note that this requirement is only for building and/or developing Cesium itself.  If you simply want to use Cesium on your website without upgrading node, you can use one of our release packages.
