### ISSUE TITLE
Cesium Inspector sandcastle example crashes

### ISSUE THREAD

**Issue by tfili** [AnalyticalGraphicsInc/cesium#5323]
```
TypeError: viewer.cesiumInspector.viewModel.update is not a function
TypeError: viewer.cesiumInspector.viewModel.update is not a function
    at http://localhost:8080/Source/Widgets/Viewer/viewerCesiumInspectorMixin.js:51:46
    at Event.raiseEvent (http://localhost:8080/Source/Core/Event.js:147:30)
    at render (http://localhost:8080/Source/Scene/Scene.js:2655:27)
    at Scene.render (http://localhost:8080/Source/Scene/Scene.js:2663:13)
    at CesiumWidget.render (http://localhost:8080/Source/Widgets/CesiumWidget/CesiumWidget.js:682:25)
    at render (http://localhost:8080/Source/Widgets/CesiumWidget/CesiumWidget.js:72:32)
```

**Comment by hpinkos** [comment]
I must have updated this in the `3d-tiles` branch but forgot to push it to master.  Thanks @tfili!
