### ISSUE TITLE
Crash in PolylineGraphics

### ISSUE THREAD

**Issue by SunBlack** [AnalyticalGraphicsInc/cesium#5345]
I have following code:

```
var pickPositions = [];
var lineStrip;
var handler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
handler.setInputAction(function(movement) {
    if (!viewer.scene.pickPositionSupported) {
        console.warn("pickPosition not supported!");
        return;
    }

    var pickedPosition = viewer.scene.pickPosition(movement.position);

    if (pickedPosition !== 'undefined') {
        pickPositions.push(pickedPosition);

        if (pickPositions.length > 1) {
            //viewer.entities.remove(lineStrip); //<- add this line here and all works fine

            lineStrip = viewer.entities.add({
                polyline : {
                    positions: pickPositions,
                    width : 10,
                    material: Cesium.Color.ROYALBLUE,
                    followSurface: true
                }
            });
        }
    }
}, Cesium.ScreenSpaceEventType.LEFT_DOUBLE_CLICK);
```

At the moment I picked 5. point Cesium is crashing. I'm getting following error:
```
RangeError: Invalid array length
RangeError: Invalid array length
    at Function.PolylineGeometry.unpack (http://localhost:8080/Source/Core/PolylineGeometry.js:248:35)
    at createPolylineGeometry (http://localhost:8080/Source/Workers/createPolylineGeometry.js:14:49)
    at createGeometry (http://localhost:8080/Source/Workers/createGeometry.js:46:30)
    at http://localhost:8080/Source/Workers/createTaskProcessorWorker.js:56:42
```
It works if I remove `lineStrip` each time before adding new `lineStrip`. So it looks like Cesium isn't handling changes in position array correctly (I have no idea why it crashes at 5 points, but not already at 3).

My expectation was an error message that altering position after it is already added to scene is not allowed - or if altering is supported no crash.

**Comment by SunBlack** [comment]
I have done some research on this issue. It crashed randomly at 5th element element because `PolylineGeometry.unpack` read a `Cartesian3` value instead of packed size of color array - so it is a out of memory exception.

If I add following code to the end of `PolylineGeometry.pack`
```
        //>>includeStart('debug', pragmas.debug);
        if (startingIndex !== array.length - 1) {
            throw new DeveloperError('given packed length did not match required packed length');
        }
        //>>includeEnd('debug');
```
It throws an error in case someone modified position or color after constructor of `PolylineGeometry` was called, so `this.packedLength` is invalid.

Now is the question. Should we just throw this exception or handle this error? I tried it to fix by a copy of data array:
```
        this._positions = positions.slice(0);
        this._colors = defined(colors) ? colors.slice(0) : undefined
```
But this seems not to be a fully fix. So in case we want to prevent this exception someone should do more research on this issue.
