### ISSUE TITLE
Crash in Cesium3DTilesetTraversal 

### ISSUE THREAD

**Issue by SunBlack** [AnalyticalGraphicsInc/cesium#5353]
On current dev I'm getting a exception in `Cesium3DTilesetTraversal`, introduced with #5254. If I ook at point cloud without zooming in all is okay. But If I zoom in it crashes - maybe if I see last level of tree.

Error message:
```
TypeError: Cannot read property 'insert' of undefined
TypeError: Cannot read property 'insert' of undefined
    at loadTile (http://localhost:8080/Source/Scene/Cesium3DTilesetTraversal.js:635:30)
    at InternalSkipTraversal.leafHandler (http://localhost:8080/Source/Scene/Cesium3DTilesetTraversal.js:568:21)
    at DFS (http://localhost:8080/Source/Scene/Cesium3DTilesetTraversal.js:764:25)
    at InternalSkipTraversal.execute (http://localhost:8080/Source/Scene/Cesium3DTilesetTraversal.js:479:9)
    at SkipTraversal.getChildren (http://localhost:8080/Source/Scene/Cesium3DTilesetTraversal.js:453:26)
    at BFS (http://localhost:8080/Source/Scene/Cesium3DTilesetTraversal.js:788:40)
    at SkipTraversal.execute (http://localhost:8080/Source/Scene/Cesium3DTilesetTraversal.js:436:9)
    at Object.selectTiles (http://localhost:8080/Source/Scene/Cesium3DTilesetTraversal.js:88:40)
    at Cesium3DTileset.update (http://localhost:8080/Source/Scene/Cesium3DTileset.js:1577:34)
    at PrimitiveCollection.update (http://localhost:8080/Source/Scene/PrimitiveCollection.js:366:27)
    at updatePrimitives (http://localhost:8080/Source/Scene/Scene.js:2421:27)
    at executeCommandsInViewport (http://localhost:8080/Source/Scene/Scene.js:2287:13)
```
`tile._requestHeap` is still `undefined` at crashing line.

**Comment by SunBlack** [comment]
I took a deeper look at it: It is caused by an exception during creating Cesium3DTile, which will be not displaed. Maybe we should add a error handling there. To reproduce it just create a child with following data:
```
"region": [
	-1.3746626099084387,
	0.6241601799339909,
	-1.3746626099084387,
	0.6241601799339909,
	225.07998657226562,
	225.07998657226562
]
```

**Comment by lilleyse** [comment]
Thanks for tracking it down. Something should check for degenerate regions before it gets to the normalization exception. I added this as an example to #5158.
