### ISSUE TITLE
Height reference is not supported without a scene.

### ISSUE THREAD

**Issue by DemonicHawk** [AnalyticalGraphicsInc/cesium#5453]
Setting the height reference for a billboard inside a billboard collection gives the following `error:`
```
Uncaught DeveloperError: Height reference is not supported without a scene.
Error
    at new DeveloperError (http://cesiumjs.org/Cesium/Source/Core/DeveloperError.js:44:19)
    at Function.Billboard._updateClamping (http://cesiumjs.org/Cesium/Source/Scene/Billboard.js:931:23)
    at Billboard._updateClamping (http://cesiumjs.org/Cesium/Source/Scene/Billboard.js:920:19)
    at new Billboard (http://cesiumjs.org/Cesium/Source/Scene/Billboard.js:167:14)
    at BillboardCollection.add (http://cesiumjs.org/Cesium/Source/Scene/BillboardCollection.js:461:17)
    at startup (<anonymous>:15:21)
    at Object.execCb (http://cesiumjs.org/Cesium/ThirdParty/requirejs-2.1.20/require.js:1678:33)
    at Module.check (http://cesiumjs.org/Cesium/ThirdParty/requirejs-2.1.20/require.js:878:51)
    at Module.<anonymous> (http://cesiumjs.org/Cesium/ThirdParty/requirejs-2.1.20/require.js:1128:34)
    at http://cesiumjs.org/Cesium/ThirdParty/requirejs-2.1.20/require.js:131:23 (on line 931 of http://cesiumjs.org/Cesium/Source/Scene/Billboard.js)
```

Manually assigning the scene with the following code snippet seems to resolve the issue:
```
billboardCollection._scene = viewer.scene;
```

Sample code:
```
var viewer = new Cesium.Viewer('cesiumContainer');
viewer.terrainProvider = new Cesium.CesiumTerrainProvider({
    url : 'https://assets.agi.com/stk-terrain/v1/tilesets/world/tiles'
});
viewer.scene.globe.depthTestAgainstTerrain = true;

var billboardCollection = new Cesium.BillboardCollection();
viewer.scene.primitives.add(billboardCollection);
billboardCollection.add({
    position : Cesium.Cartesian3.fromDegrees(-122.1958, 46.1915),
    image : '../images/facility.gif',
    heightReference : Cesium.HeightReference.CLAMP_TO_GROUND
});
```

I've tested versions on Sandcastle dating all the way back to 1.10 when the feature was first introduced, but they all seem to have the same error..  I should also mention I don't seem to get the error when running outside of Sandcastle, although heightReference does not seem to work properly

**Comment by mramato** [comment]
As per the documentation (http://cesiumjs.org/Cesium/Build/Documentation/BillboardCollection.html?#BillboardCollection) you need to pass the scene as a constructor option into billboard collection if you want to use height reference (the error message could probably be a little better):

```javascript
var billboardCollection = new Cesium.BillboardCollection({ scene: viewer.scene});
```

If you are using the minified Cesium.js, you will not see the error because that is the release version which has developer errors removed.  When developing against the combined Cesium.js file, we recommend using the version in `Build\CesiumUnminified` which will show all errors and only switching to `Build\Cesium` for production.
