### ISSUE TITLE
error on install cesium

### ISSUE THREAD

**Issue by omeric4c** [AnalyticalGraphicsInc/cesium#5454]
D:\Cesium-1.34>npm install cesium
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "cesium"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install cesium as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Cesium-1.34\npm-debug.log

**Comment by omeric4c** [comment]
D:\Cesium-1.34>npm install
module.js:96
    throw e;
    ^

SyntaxError: Error parsing C:\Program Files\nodejs\node_modules\npm\node_modules
\inherits\package.json: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at readPackage (module.js:92:52)
    at tryPackage (module.js:102:13)
    at Function.Module._findPath (module.js:186:20)
    at Function.Module._resolveFilename (module.js:467:25)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules
\readable-stream\lib\_stream_readable.js:41:17)
    at Module._compile (module.js:570:32)
module.js:96
    throw e;
    ^

SyntaxError: Error parsing C:\Program Files\nodejs\node_modules\npm\node_modules
\inherits\package.json: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at readPackage (module.js:92:52)
    at tryPackage (module.js:102:13)
    at Function.Module._findPath (module.js:186:20)
    at Function.Module._resolveFilename (module.js:467:25)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules
\readable-stream\lib\_stream_readable.js:41:17)
    at Module._compile (module.js:570:32)

**Comment by mramato** [comment]
@omeric4c It looks like you are using a downloaded zip release of Cesium and then trying to run `npm install cesium` in that directory.  That definitely won't work as the error message indicates.  You should be running `npm install` only.

The second error looks like there may have been an issue with Node on your end.  Try running `npm cache clean` and then starting with a freshly unpacked zip before running `npm install` again.

Finally, if you still need help, please ask a question [on the forum](http://cesiumjs.org/forum.html) rather than posting here.  Thanks.
