### ISSUE TITLE
Models broken when Globe is disabled

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#5638]
The below code snippet fails because globe is false, removing the line fixes the example.  This is a regression but I'm not sure which version is stopped working in.  (Note you have to remove the line, not set it to true because of the way Viewer options work.)

```javascript
var viewer = new Cesium.Viewer('cesiumContainer', {
    globe: false
});


var position = Cesium.Cartesian3.fromDegrees(-123.0744619, 44.0503706, 5000);
var heading = Cesium.Math.toRadians(135);
var pitch = 0;
var roll = 0;
var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
var orientation = Cesium.Transforms.headingPitchRollQuaternion(position, hpr);

var entity = viewer.entities.add({
    position : position,
    orientation : orientation,
    model : {
        uri : '../../SampleData/models/CesiumAir/Cesium_Air.glb',
        minimumPixelSize : 128,
        maximumScale : 20000
    }
});
viewer.trackedEntity = entity;
```

Here's the callstack

```
TypeError: Cannot read property 'terrainProviderChanged' of undefined
    at Scene.get (http://cesiumjs.org/Cesium/Source/Scene/Scene.js:919:34)
    at new Model (http://cesiumjs.org/Cesium/Source/Scene/Model.js:532:18)
    at Function.Model.fromGltf (http://cesiumjs.org/Cesium/Source/Scene/Model.js:1203:21)
    at ModelVisualizer.update (http://cesiumjs.org/Cesium/Source/DataSources/ModelVisualizer.js:121:31)
    at DataSourceDisplay.update (http://cesiumjs.org/Cesium/Source/DataSources/DataSourceDisplay.js:262:37)
    at Viewer._onTick (http://cesiumjs.org/Cesium/Source/Widgets/Viewer/Viewer.js:1572:49)
    at Event.raiseEvent (http://cesiumjs.org/Cesium/Source/Core/Event.js:142:30)
    at Clock.tick (http://cesiumjs.org/Cesium/Source/Core/Clock.js:308:21)
    at CesiumWidget.render (http://cesiumjs.org/Cesium/Source/Widgets/CesiumWidget/CesiumWidget.js:685:43)
    at render (http://cesiumjs.org/Cesium/Source/Widgets/CesiumWidget/CesiumWidget.js:71:32)
```

This is probably multiple trivial bugs.  Scene should not access the globe unless it's defined and Model should not subscribe to the terrainChanged event if it's undefined.

**Comment by mramato** [comment]
@ggetz this is probably a quickie if you have some time.
