### ISSUE TITLE
IE crashes for 3D tiles PointCloudBatched tileset

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5700]
Open up the [3D Tiles Formats](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=3D%20Tiles%20Formats.html&label=All) sandcastle demo in IE and select 'PointCloudBatched'

```
An error occurred while rendering. Rendering has stopped.
TypeError: Object doesn't support property or method 'tile_translucentCommand'
TypeError: Object doesn't support property or method 'tile_translucentCommand'
   at ShaderProgram.prototype._setUniforms (http://cesiumjs.org/Cesium/Source/Renderer/ShaderProgram.js:483:17)
   at continueDraw (http://cesiumjs.org/Cesium/Source/Renderer/Context.js:916:9)
   at Context.prototype.draw (http://cesiumjs.org/Cesium/Source/Renderer/Context.js:957:9)
   at DrawCommand.prototype.execute (http://cesiumjs.org/Cesium/Source/Renderer/DrawCommand.js:502:9)
   at executeCommand (http://cesiumjs.org/Cesium/Source/Scene/Scene.js:1647:13)
   at executeCommands (http://cesiumjs.org/Cesium/Source/Scene/Scene.js:1936:17)
   at executeCommandsInViewport (http://cesiumjs.org/Cesium/Source/Scene/Scene.js:2298:9)
   at updateAndExecuteCommands (http://cesiumjs.org/Cesium/Source/Scene/Scene.js:2151:17)
   at render (http://cesiumjs.org/Cesium/Source/Scene/Scene.js:2627:9)
   at Scene.prototype.render (http://cesiumjs.org/Cesium/Source/Scene/Scene.js:2666
```

**Comment by hpinkos** [comment]
There are two IE test failures caused by the same `tile_translucentCommand` error: 

* Scene/Cesium3DTileset verify batched points statistics
* Scene/Cesium3DTileset debugColorizeTiles for pnts with batch table

(I also noted these in #2860)

**Comment by lilleyse** [comment]
Both the Sandcastle demo and tests in IE seem to have been fixed.
