### ISSUE TITLE
3D tiles stops working after changing the scene mode

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#5729]
http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=3D%20Tiles%20Feature%20Styling.html&label=Showcases

1. Switch to 2D
2. Zoom back into manhatten
3. Switch back to 3D
4. When you zoom back to manhatten, you'll notice a lot of the tiles no longer pop in

**Comment by ggetz** [comment]
In fact, during step 2, I get this error:

```
An error occurred while rendering.  Rendering has stopped.
TypeError: Cannot read properties of undefined (reading 'longitude')
TypeError: Cannot read properties of undefined (reading 'longitude')
    at GeographicProjection.project (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:12070:29)
    at Transforms.wgs84To2DModelMatrix (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:24060:43)
    at computeModelMatrix2D (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:122360:39)
    at ModelSceneGraph.updateModelMatrix (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:122595:7)
    at updateSceneGraph (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:125395:18)
    at Model.update (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:125109:5)
    at Model3DTileContent.update (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:126053:11)
    at updateContent (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:140586:20)
    at Cesium3DTile.update (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:140608:5)
    at updateTiles (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:144154:12)
  ```
