### ISSUE TITLE
sampleTerrain test failures in master

### ISSUE THREAD

**Issue by pjcozzi** [AnalyticalGraphicsInc/cesium#5761]
@ggetz server issue?

```
  Core/sampleTerrain
    ✗ queries heights from Small Terrain
	Expected undefined to be greater than 5000.
	    at Specs/Core/sampleTerrainSpec.js:42:41
	    at Promise.then (Source/ThirdParty/when.js:196:34)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
	    at _resolve (Source/ThirdParty/when.js:333:4)
	Expected undefined to be less than 10000.
	    at Specs/Core/sampleTerrainSpec.js:43:41
	    at Promise.then (Source/ThirdParty/when.js:196:34)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
	    at _resolve (Source/ThirdParty/when.js:333:4)
	Expected undefined to be greater than 5000.
	    at Specs/Core/sampleTerrainSpec.js:44:41
	    at Promise.then (Source/ThirdParty/when.js:196:34)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
	    at _resolve (Source/ThirdParty/when.js:333:4)
	Expected undefined to be less than 10000.
	    at Specs/Core/sampleTerrainSpec.js:45:41
	    at Promise.then (Source/ThirdParty/when.js:196:34)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
	    at _resolve (Source/ThirdParty/when.js:333:4)
```

**Comment by mramato** [comment]
This is definitely a missing rewrite from the old cesiumjs.org.

**Comment by pjcozzi** [comment]
Gotcha.  @ggetz can you please look at this soon?

**Comment by ggetz** [comment]
Yes, I'm looking at this right now!
