### ISSUE TITLE
Invalid array length RangeError

### ISSUE THREAD

**Issue by truefunrun** [AnalyticalGraphicsInc/cesium#5811]
Hi all, I encountered such a problem with `Invalid array length RangeError`

```
RangeError: Invalid array length RangeError: Invalid array length 
at Me (...dist/Cesium.js:583:25726) 
at Ne (...dist/Cesium.js:583:28447)
 at Ke (...dist/Cesium.js:584:6626) 
 at Qe (...dist/Cesium.js:584:4622)
 at ot (...dist/Cesium.js:584:11528)
 at Ee.render (...dist/Cesium.js:584:19422) 
 at A.render (...dist/Cesium.js:596:18399)
 at t (...dist/Cesium.js:596:6348)
```
Sorry, but I'm not use source of Cesium library , so I use webpack for build my application. And with source my webpack building not worked.
I use `"cesium": "1.36.0"`

**Comment by ggetz** [comment]
Hi @truefunrun, please ask questions over at the [Cesium Forum](https://groups.google.com/forum/#!forum/cesium-dev). Cesium's a big project, so we use GitHub for feature requests and bug tracking exclusively. Thanks!

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!forum/cesium-dev

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/5811 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.


__I am a bot who helps you make Cesium awesome!__ Thanks again.

**Comment by sharseema** [comment]
Hi @truefunrun  ,I have also same error
`An error occurred while rendering. Rendering has stopped.
RangeError: Invalid array length
RangeError: Invalid array length
    at Me (http://localhost/cesium/Build/Cesium/Cesium.js:552:18985)
    at Ne (http://localhost/cesium/Build/Cesium/Cesium.js:552:21706)
    at Ke (http://localhost/cesium/Build/Cesium/Cesium.js:553:84)
    at Qe (http://localhost/cesium/Build/Cesium/Cesium.js:552:30061)
    at ot (http://localhost/cesium/Build/Cesium/Cesium.js:553:4958)
    at Ee.render (http://localhost/cesium/Build/Cesium/Cesium.js:553:12911)
    at A.render (http://localhost/cesium/Build/Cesium/Cesium.js:566:8588)
    at t (http://localhost/cesium/Build/Cesium/Cesium.js:565:23673)`
I have Cesium 1.39 library.I tried with other Cesium version and also cleared all cache but still its not working.please help me,Thanks.

**Comment by emackey** [comment]
Please use the forum, or search for existing issues, before opening new issues.  The "invalid array length" error is almost always the result of loading invalid data into Cesium, and has been reported multiple times before (for example #1477 and #2853).  If you need help fixing your code, please ask on the forum, thanks!
