### ISSUE TITLE
Camera Controller can go underground

### ISSUE THREAD

**Issue by ggetz** [AnalyticalGraphicsInc/cesium#5837]
Move the camera while terrain is still loading in:

![image](https://user-images.githubusercontent.com/4439461/30563627-744ba3cc-9c90-11e7-92ba-a9808323561d.png)

Appeared after https://github.com/AnalyticalGraphicsInc/cesium/pull/5603

Reported on the forum: https://groups.google.com/forum/#!topic/cesium-dev/50CK4haCIiw

**Comment by mramato** [comment]
Are you sure #5603 caused this?  We specifically allow the camera to go underground during load because otherwise flights and abrupt camera changes wouldn't work correctly.  See #4105.  If this is differently, please explain how.

**Comment by ggetz** [comment]
@mramato If this is intended behavior, I'm fine with closing this.

**Comment by mramato** [comment]
Please feel free to re-open if there is some additional context I'm missing.  You might also want to follow up on the forum post.  Thanks.

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/50CK4haCIiw

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/5837 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.


__I am a bot who helps you make Cesium awesome!__ Thanks again.

**Comment by wallw-bits** [comment]
#5603 absolutely caused a change in behavior. 

I commented in #5603 but I'll copy it here:
> The additional call to camera.setView() should not affect its position, at least according to how I understand the documentation. However, it most certainly is affecting the position as commenting out that one line fixes the problem (but leaves #4639 unresolved in some cases).

**Comment by ZacBrownBand** [comment]
Any update on this issue?

**Comment by ggetz** [comment]
@ZacBrownBand, no additional updates. If you could [contribute](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors) a fix, or continue to narrow down what the problem is, it would help move things along and we would greatly appreciate it!

**Comment by gberaudo** [comment]
@ZacBrownBand, I created https://github.com/AnalyticalGraphicsInc/cesium/pull/6012 which also fixes this.

**Comment by ggetz** [comment]
Reported on the forum: https://groups.google.com/forum/#!topic/cesium-dev/cPbtbShkSOQ

**Comment by ggetz** [comment]
Reported on the forum: https://groups.google.com/forum/#!topic/cesium-dev/Sn5R5FzOr1k

**Comment by ggetz** [comment]
Reported on the forum: https://groups.google.com/forum/#!topic/cesium-dev/TDMwlbT0xBE

**Comment by hpinkos** [comment]
Also reported by @fgamezc in #6581

**Comment by hpinkos** [comment]
Also reported by @safa833 in #6623

**Comment by hpinkos** [comment]
Also reported by @miniergouzi in #6856

**Comment by OmarShehata** [comment]
Reported [in this forum thread](https://groups.google.com/d/msg/cesium-dev/Mq4i8gC6eAE/-jeRGSn6CAAJ) with a video and how to recreate.

**Comment by lilleyse** [comment]
Came up again in the context of navigating around a point cloud and ending up underground accidentally. I'm curious if anyone knows of any workarounds for this.

**Comment by mramato** [comment]
@lilleyse the problem is pretty nuanced, You can modify the end of Camera.update to always set `_suspendTerrainAdjustment` to false and always call `_adjustHeightForTerrain` and that would prevent the camera from ever going under terrain, however functions like zoomTo/FlyTo will not work as expected near the ground because they will "bump into" lower res terrain and end up at a higher altitude than desired.

**Comment by mramato** [comment]
We also tweaked this behavior in master to be better, so I would try that out if you aren't already.

**Comment by bmr74** [comment]
I think the adjustment for terrain would be better if it were invoked by the ScreenSpaceCameraController instead of the camera itself.   When programmatically controlling the camera, you don't want the camera doing things you didn't tell it explicitly to do.  So the responsibility is ill-placed, it should be with the user control of the camera.

Meanwhile this can fixed like so:

var viewer = new Cesium.Viewer('cesiumContainer');

viewer.camera.changed.addEventListener(
    function() {
        if (viewer.camera._suspendTerrainAdjustment && viewer.scene.mode === Cesium.SceneMode.SCENE3D) {
            viewer.camera._suspendTerrainAdjustment = false;
            viewer.camera._adjustHeightForTerrain();
        }
    }
);

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=jVFdS8MwFP0roQ9bC3KL+Lh2KHXiw9SHiU8FuUtut2iajHx0TPG/m64bbArieUnuyfm4kA4t6yRtybKSadqyipwMLbzsuXTM92NltEepyY6zSa1rPTiAY0sWga9Rr0gACjHrSPu5dJ6iOK01i2iC5l4anWbsc2B6yIal5zGvLrgNafFM1sayG/EWnG9jHhuNDjuC4zEYWiOIlWV5XHbRsw+RhEU1e5xd3Z419fhvU8kaVI4mf7pxr78nuVr7O2MPKWl24voarvHIJslFUji/UzQdyGvZboz1LFiVAuSe2o1CTy5fBv5OHrhzfVSRH02FkB2ToqyTH79RJ4wrdC6+NEGphfygOpkWedSf2ZRBIfXqqSOrcNdL1pfT+UACQJHH8bfLG6OWaE8SvwE

**Comment by miniergouzi** [comment]
@bmr74    在您的代码中进行鼠标操作时的险地问题得到解决，但是鼠标使用缩进功能的时候还是会出现类似问题。

**Comment by miniergouzi** [comment]
@bmr74    

This problem occurs when the mouse pulley is indented.

![64b0euqw67k nrt d alm 9](https://user-images.githubusercontent.com/40375251/48457224-d8ceb380-e7fc-11e8-897d-8805985d711e.png)

**Comment by bmr74** [comment]
@miniergouzi  my fix should help, but is not complete solution.  You can still go under the terrain, it just recovers much faster.  One thing I did was to also limit the pitch, which is fine for my particular application.  You could also add a min zoom distance, if that is acceptable in your application.

I can't see the full stack trace and I have not seen that problem.  What browser/version are you using?  Can you provide the complete stack trace?

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=rVRdb5swFP0rVh5akDqTrW8Fok1Zpk1rl6qJuhekyIFL8GZsZBu6fuS/zwYSAmmrappfMJdzju8995qKSFRRuAOJQsThDk1B0TLHt3XMOY3r16ngmlAO8tT1Ix7xyrByyq+pjjPDe9eSrojO8PW31fx2drNa/pz7LZL82SHH/p78Fegm0yb2YTxuROsjcUxykATHGeEbSDBJklkFXF9SpcFk4EQcmZWWPNZUcMdFj03ELpoipy+zUqUqgCdLkNJU8Cn5VSqdGz10ctIWjlVshHEuEkBhGO4cWNjolQnixXT2Y3b+uXeSXW89KUQpYQr8V9mkxjemfBGyVXHcA9a223Y7z0PfAQrU6CDKEUESiBKcrBmgojZeWi87ju1A0Xakn0YdrbtxaGmDnXSNfHpq+cF+DF5ypzFXxRKALwoSw7Q+yU6UFIwZBNSZLik7dKqvZYqMGckLpLO2pP53mh7naBJCfZRdu7J3MH+A2SIwCXSCrxTYk2tBgx5vh4VY5xNQmnJipxftp21KpDY7ws9xKkV+QxKzV87xiYN+CUWtkKWLjSRFRmPMBN9QXSZw9m90k9oL7PqCG+ucN8hk9SifdVfddY/62pdRoO1vx3nG5wPPLg5fnslRSGouXQt9bDp00TZqO2iP6/+PmdWyhONrah6uPzobBUrfM5g0wY80L4TUqJTMwdjTkBfGblDeuox/g8axUjanwNuRgoRWiCZhNBr8iaORvRJKmS9pydiCPkA0mgSewfdoTJhR4pt5BZKRewvJ3k8umyDGOPDM6zFLC8HWRB4o/gU

**Comment by ohadmanor** [comment]
> viewer.camera.changed.addEventListener(
> function() {
> if (viewer.camera._suspendTerrainAdjustment && viewer.scene.mode === Cesium.SceneMode.SCENE3D) {
> viewer.camera._suspendTerrainAdjustment = false;
> viewer.camera._adjustHeightForTerrain();
> }
> }
> );

That's work great! it fix the problem.

**Comment by bbehling-trimble** [comment]
I'm still able to get the camera to go under the terrain in Cesium v1.55. Is the fix mentioned by @bmr74 going to be permanent? Seems incorrect to use 'private' class members.

**Comment by bbehling-trimble** [comment]
Also see this error occur:

TypeError: Cannot read property 'southwest' of undefined
TypeError: Cannot read property 'southwest' of undefined
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154816:40)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154839:7)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154843:7)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154843:7)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154837:7)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154843:7)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154844:7)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154837:7)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154843:7)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154837:7)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154837:7)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154830:9)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154837:7)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154824:9)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154824:9)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154830:9)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)
    at visitIfVisible (http://192.168.56.4:3000/static/js/17.chunk.js:154859:14)
    at visitVisibleChildrenNearToFar (http://192.168.56.4:3000/static/js/17.chunk.js:154824:9)
    at visitTile (http://192.168.56.4:3000/static/js/17.chunk.js:154733:7)

**Comment by popoleeMaster** [comment]
I still have this problem with the latest version. In the default exemple, just press the center button on a mouse, drag the mouse around, and release, you will have such a wierd view that was not at all what is intended to be.

**Comment by engineerhe** [comment]
@bmr74 your answer does work，Strong!

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!topic/cesium-dev/50CK4haCIiw
https://groups.google.com/forum/#!topic/cesium-dev/cPbtbShkSOQ
https://groups.google.com/forum/#!topic/cesium-dev/Sn5R5FzOr1k
https://groups.google.com/forum/#!topic/cesium-dev/TDMwlbT0xBE
https://groups.google.com/d/msg/cesium-dev/Mq4i8gC6eAE/-jeRGSn6CAAJ

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/issues/5837 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
