### ISSUE TITLE
The glTF model of "Polly" does not loading correctly

### ISSUE THREAD

**Issue by cx20** [AnalyticalGraphicsInc/cesium#5891]
The project "Polly" seems to have been created to introduce all new features of glTF 2.0.
https://www.youtube.com/watch?v=l7TB1O51X_M

However, I tried [project_polly.gltf](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/polly/project_polly.gltf) displayed in Cesium.js, model seems not to be displayed correctly.
Cesium.js + project_polly.gltf result:
http://jsdo.it/cx20/u7sb

```
Cesium.js:566 
An error occurred while rendering.  Rendering has stopped.
undefined
TypeError: Cannot read property 'x' of undefined
TypeError: Cannot read property 'x' of undefined
    at Function.u.dot (https://cdn.rawgit.com/cx20/gltf-test/68db7eba/libs/cesium/1.38/Cesium.js:489:16758)
    at Function.u.fastSlerp (https://cdn.rawgit.com/cx20/gltf-test/68db7eba/libs/cesium/1.38/Cesium.js:489:18762)
    at Function.u.fastSquad (https://cdn.rawgit.com/cx20/gltf-test/68db7eba/libs/cesium/1.38/Cesium.js:489:19154)
    at l._evaluateFunction (https://cdn.rawgit.com/cx20/gltf-test/68db7eba/libs/cesium/1.38/Cesium.js:505:27224)
    at l.evaluate (https://cdn.rawgit.com/cx20/gltf-test/68db7eba/libs/cesium/1.38/Cesium.js:505:27758)
    at Array.<anonymous> (https://cdn.rawgit.com/cx20/gltf-test/68db7eba/libs/cesium/1.38/Cesium.js:527:23101)
    at p (https://cdn.rawgit.com/cx20/gltf-test/68db7eba/libs/cesium/1.38/Cesium.js:526:30193)
    at d.update (https://cdn.rawgit.com/cx20/gltf-test/68db7eba/libs/cesium/1.38/Cesium.js:527:257)
    at Ee.update (https://cdn.rawgit.com/cx20/gltf-test/68db7eba/libs/cesium/1.38/Cesium.js:528:23316)
    at a.update (https://cdn.rawgit.com/cx20/gltf-test/68db7eba/libs/cesium/1.38/Cesium.js:549:22895)
```

**Comment by ggetz** [comment]
Thanks @cx20! This is already on our roadmap for glTF 2.0 support, #4009.
