### ISSUE TITLE
webpack3 issues with cesium

### ISSUE THREAD

**Issue by tamarmot** [AnalyticalGraphicsInc/cesium#6049]
Just followed the excellent instructions to set cesium up to be webpacked.  This worked fine in webpack 1, but when I upgraded to webpack 3 I get the following warnings from TaskProcessor.js:

```
WARNING in ./node_modules/cesium/Source/Core/TaskProcessor.js
140:80-87 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
    at CommonJsRequireContextDependency.getWarnings (/home/xgds/xgds_basalt/sextantwebapp/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/home/xgds/xgds_basalt/sextantwebapp/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/home/xgds/xgds_basalt/sextantwebapp/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/home/xgds/xgds_basalt/sextantwebapp/node_modules/webpack/lib/Compiler.js:502:17)
    at /home/xgds/xgds_basalt/sextantwebapp/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/xgds/xgds_basalt/sextantwebapp/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/xgds/xgds_basalt/sextantwebapp/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
 @ ./node_modules/cesium/Source/Core/TaskProcessor.js
 @ ./node_modules/cesium/Source/Core/HeightmapTerrainData.js
 @ ./node_modules/cesium/Source/Core/EllipsoidTerrainProvider.js
 @ ./node_modules/cesium/Source/Cesium.js
 @ ./app/plan/plan.js
 @ ./app/index.js
 @ multi ./app/index.js


```

**Comment by hpinkos** [comment]
Hi @tamarmot! Have you see our Cesium + Webpack tutorial? https://cesiumjs.org/tutorials/cesium-and-webpack/

The tutorial code is in a demo repo here which looks like it's using webpack 3: https://github.com/AnalyticalGraphicsInc/cesium-webpack-example

**Comment by ggetz** [comment]
Hi @tamarmot, you can submit issues like over at the [cesium-webpack-example](https://github.com/AnalyticalGraphicsInc/cesium-webpack-example) repository where the recommended configuration is.

The above is a warning that won't interfere with the build process, but you can disable by using the [context replacement plugin](https://github.com/webpack/docs/wiki/list-of-plugins#contextreplacementplugin)

**Comment by tamarmot** [comment]
Hi Hannah & Gabby -- thanks for your quick response!

I definitely see that I can run my app even with the warning.

 The warning led me to believe the issue was from within TaskProcessor,js.
I'll take a look at the ContextReplacementPlugin.

Thanks!
Tamar
