### ISSUE TITLE
Occasional spec failure

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6178]
One of the new scene tests `time change exceeding maximumRenderTimeChange causes a new frame to be rendered in ` seems to occasionally fail, I think the problem is the test should be using `toEqualEpsilon` to compare JulianDates, and instead it's using `toEquals`.

```
requestRenderMode
     Scene/Scene
     Expected 2018-02-01T21:06:03.9370000000053551Z to equal 2018-02-01T21:04:23.9370000000017171Z.
    at Specs/Scene/SceneSpec.js:1571:38
    at UserContext.<anonymous> (Specs/customizeJasmine.js:76:30)
```

CC @ggetz

**Comment by mramato** [comment]
Master just failed too: https://travis-ci.org/AnalyticalGraphicsInc/cesium/builds/336282682
