### ISSUE TITLE
Cesium.Math.toRadians(X) may or may not trigger this error 

### ISSUE THREAD

**Issue by davidbuzz** [AnalyticalGraphicsInc/cesium#6187]
error text from sandcastle: 
-----------------------------------------
An error occurred while rendering.  Rendering has stopped.
undefined
DeveloperError: normalized result is not a number
Error
    at new DeveloperError (https://cesiumjs.org/Cesium/Source/Core/DeveloperError.js:43:19)
    at Function.Cartesian3.normalize (https://cesiumjs.org/Cesium/Source/Core/Cartesian3.js:421:19)
    at computeTriangleAttributes (https://cesiumjs.org/Cesium/Source/Core/GeometryPipeline.js:1948:24)
    at splitLongitudeTriangles (https://cesiumjs.org/Cesium/Source/Core/GeometryPipeline.js:2129:17)
    at Object.GeometryPipeline.splitLongitude (https://cesiumjs.org/Cesium/Source/Core/GeometryPipeline.js:2553:17)
    at geometryPipeline (https://cesiumjs.org/Cesium/Source/Scene/PrimitivePipeline.js:134:38)
    at Object.PrimitivePipeline.combineGeometry (https://cesiumjs.org/Cesium/Source/Scene/PrimitivePipeline.js:278:26)
    at loadSynchronous (https://cesiumjs.org/Cesium/Source/Scene/Primitive.js:1216:40)
    at Primitive.update (https://cesiumjs.org/Cesium/Source/Scene/Primitive.js:1772:17)
    at DebugCameraPrimitive.update (https://cesiumjs.org/Cesium/Source/Scene/DebugCameraPrimitive.js:221:33)

javascript code from sandcastle to demonstrate the issue: 
--------------------------------------------------
var viewer = new Cesium.Viewer('cesiumContainer');

    //var heading = Cesium.Math.toRadians(-1); // works
    //var heading = Cesium.Math.toRadians(0); // fails
    //var heading = Cesium.Math.toRadians(1); // fails
    //var heading = Cesium.Math.toRadians(2); // works
    //var heading = Cesium.Math.toRadians(3); // fails
    //var heading = Cesium.Math.toRadians(4); // works
    var heading = Cesium.Math.toRadians(5); // fails
    //var heading = Cesium.Math.toRadians(6); // works

    var pitch = 0;
    var roll = 0;

    //var camera = viewer.camera;
    var scene = viewer.scene;

	var camera = new Cesium.Camera(scene);

     camera.setView({
        destination : Cesium.Cartesian3.fromDegrees(-123.0744619, 44.0503706,30),
        orientation: {
            heading : heading,
            pitch : pitch,
            roll : roll
        }
    }); 
	
scene.primitives.add(new Cesium.DebugCameraPrimitive({
	  camera : camera,
	  color : Cesium.Color.AQUA
	 }));

**Comment by davidbuzz** [comment]
given that changing .toRadians(6) to .toRadians(5) is all it takes to trigger this error, I consider it pretty serious.

**Comment by ggetz** [comment]
I don't think this is being caused by `Cesium.Math`toRadians`, as removing this block does not throw the error.

```
scene.primitives.add(new Cesium.DebugCameraPrimitive({
camera : camera,
color : Cesium.Color.AQUA
}));
```

This probably has to do with the `DebugCameraPrimitve`.

**Comment by mramato** [comment]
This may be a dupe (or same root cause) as #4801.

**Comment by hpinkos** [comment]
Nope, the problem with this one is the numbers are too big.  `barycentricCoordinates` is loosing precision because the dot products of the coordinates are too big, so [all these dot products](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/barycentricCoordinates.js#L69-L73) are resolving to the same value (~344 quadrillion). 

Then, since all those values are equal, there's a divide by zero on [line 76](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/barycentricCoordinates.js#L76), resulting in NaNs

**Comment by hpinkos** [comment]
@davidbuzz like @ggetz suspected, the problem is with the `DebugCameraPrimitive`, not with `toRadians`

**Comment by davidbuzz** [comment]
Yes, I'm aware that without the 'DebugCameraPrimitive' the problem doesn't seem to manifest, which is why  I included it in the code needed to demonstrate the issue.  :-)

**Comment by hpinkos** [comment]
> As far as I can tell I'm not using DebugCameraPrimitive.

@phazor if you're not using `DebugCameaPrimitive`, can you paste a code example with the geometry you are using that reproduces this issue?  I'm not sure of a workaround for this right now

**Comment by phazor** [comment]
Unfortunately the geometries are time-dependent + generated, and it can be hours before the error manifests. Next time I catch it I'll try to extract the full geometry that's being rendered.

In the meantime, I have a rather ugly workaround that at least allows the cesium viewer to jump past an 'expected' `DeveloperError`:
https://cesiumjs.org/Cesium/Apps/Sandcastle/?src=Hello%20World.html&label=Showcases&gist=15bca861811d7c2115af2285e57f0322

This is the crux of it:
```
viewer.scene.renderError.addEventListener(() => {
    // Retry every 10 milliseconds. Progress the clock accordingly in case it's an issue with the current frame.
    setTimeout(() => {
        viewer.clock.currentTime = Cesium.JulianDate.addSeconds(viewer.clock.currentTime, 0.01, new Cesium.JulianDate()); // skip forward 10ms
        viewer.timeline.updateFromClock();
        viewer.useDefaultRenderLoop = true; // restart rendering        
    }, 10);
});
```

**Comment by hpinkos** [comment]
Gotcha.  Yeah, let me know when you have an update.   Thanks @phazor!

**Comment by mramato** [comment]
If you're only working in 3D, then there may be a workaround.  Geometries are only split for 2D and CV scenes, so can pass `scene3DOnly: true` to the Viewer constructor and the problematic code shouldn't execute at all (unless the bug is a very different issue than I think it is): https://cesiumjs.org/Cesium/Build/Documentation/Viewer.html#Viewer  Setting this flag is good practice either way if you are only using 3D.

If you are using 2D/CV, then @hpinkos is right and there is no good workaround.
