### ISSUE TITLE
cesium concierge has gone quiet

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6354]
@ggetz are you looking into this?

**Comment by mramato** [comment]
@ggetz, it appears something may have changed on the GitHub API side of things, the log is full of errors.  Either that or the server just needs a reboot because of the AWS outages earlier.  Let me know if you need help debugging tomorrow, but I assume we want this fixed ASAP (CC @pjcozzi).

```
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Unhandled rejection SyntaxError: Unexpected token a in JSON at position 14966
    at Object.parse (native)
    at /var/app/lib/commentOnOpenedPullRequest.js:113:28
    at tryCatcher (/var/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
SyntaxError: Unexpected token a in JSON at position 14966
    at Object.parse (native)
    at /var/app/lib/commentOnOpenedPullRequest.js:113:28
    at tryCatcher (/var/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by pjcozzi** [comment]
Sooner is better, but let's discuss if the scope is somehow large.

**Comment by ggetz** [comment]
I'll take a look and see what all is needed, hopefully it's just the outages. Ran a quick test yesterday and it was still successfully commenting on closed issues.

**Comment by ggetz** [comment]
It looks like an error parsing `CLA.json` due to a typo, I'll add some error checking so this doesn't happen in the future.

**Comment by pjcozzi** [comment]
I think the error checking should happen in CI, just like glTF, 3D Tiles, etc.

**Comment by mramato** [comment]
We can check in both places, but I agree with @ggetz in that cesium-concierge should definitely have an error check as well, so that the actual problem is obviously logged if it gets bad data as opposed to the obtuse callstack we had.

**Comment by pjcozzi** [comment]
OK, I guess it is also good if others are using concierge without our CI.

Just keep it quick and simple please.
