### ISSUE TITLE
Terrain Clipping Planes Sandcastle example is broken in master

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6366]
http://localhost:8080/Apps/Sandcastle/index.html?src=Terrain%20Clipping%20Planes.html&label=Showcases

The following error happens when you switch to the `St. Helens` example

```js
DeveloperError: This object was destroyed, i.e., destroy() was called.
Error
    at new DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:43:19)
    at PrimitiveCollection.throwOnDestroyed (http://localhost:8080/Source/Core/destroyObject.js:45:19)
    at Batch.update (http://localhost:8080/Source/DataSources/StaticOutlineGeometryBatch.js:129:32)
    at StaticOutlineGeometryBatch.update (http://localhost:8080/Source/DataSources/StaticOutlineGeometryBatch.js:330:35)
    at GeometryVisualizer.update (http://localhost:8080/Source/DataSources/GeometryVisualizer.js:255:36)
    at DataSourceDisplay.update (http://localhost:8080/Source/DataSources/DataSourceDisplay.js:274:37)
    at Viewer._onTick (http://localhost:8080/Source/Widgets/Viewer/Viewer.js:1583:49)
    at Event.raiseEvent (http://localhost:8080/Source/Core/Event.js:146:30)
    at Clock.tick (http://localhost:8080/Source/Core/Clock.js:307:21)
    at CesiumWidget.render (http://localhost:8080/Source/Widgets/CesiumWidget/CesiumWidget.js:695:43)
```

Thanks for catching this @hanbollar!

**Comment by hpinkos** [comment]
This was probably my fault.  Looking into this now
