### ISSUE TITLE
cesium cannot read property toBytes of undefined

### ISSUE THREAD

**Issue by gezonthenet** [AnalyticalGraphicsInc/cesium#6369]
Upgrading from Cesium 1.42 to 1.43 results in a CZML file failing to animate with the error "cesium cannot read property toBytes of undefined". It appears to be something to do with the material color handling.

The attached file works in 1.42, but fails in 1.43. 

I zipped the czml file uploading. 

[20180326_135831_ALL_A_RRC_Attempt.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/1846332/20180326_135831_ALL_A_RRC_Attempt.zip)

**Comment by shunter** [comment]
Your CZML is invalid.  Loading it produces:

```
DeveloperError: Expected longitude to be typeof number, actual typeof was string
Error
    at new DeveloperError (https://cesiumjs.org/Cesium/Source/Core/DeveloperError.js:43:19)
    at Object.Check.typeOf.number (https://cesiumjs.org/Cesium/Source/Core/Check.js:77:19)
    at Function.Cartesian3.fromDegrees (https://cesiumjs.org/Cesium/Source/Core/Cartesian3.js:796:22)
    at Function.Cartesian3.fromDegreesArrayHeights (https://cesiumjs.org/Cesium/Source/Core/Cartesian3.js:951:40)
    at processPositionsPacketData (https://cesiumjs.org/Cesium/Source/DataSources/CzmlDataSource.js:1237:50)
    at processPositions (https://cesiumjs.org/Cesium/Source/DataSources/CzmlDataSource.js:1256:13)
    at Array.processPolygon (https://cesiumjs.org/Cesium/Source/DataSources/CzmlDataSource.js:1755:9)
    at processCzmlPacket (https://cesiumjs.org/Cesium/Source/DataSources/CzmlDataSource.js:1892:36)
    at Function.CzmlDataSource._processCzml (https://cesiumjs.org/Cesium/Source/DataSources/CzmlDataSource.js:2285:17)
    at loadCzml (https://cesiumjs.org/Cesium/Source/DataSources/CzmlDataSource.js:2017:24)`
```

Looking at the file, your position data is incorrectly specified as strings.

**Comment by shunter** [comment]
Here's the reformatted CZML file.

[20180326_135831_ALL_A_RRC_Attempt.txt](https://github.com/AnalyticalGraphicsInc/cesium/files/1848058/20180326_135831_ALL_A_RRC_Attempt.txt)

**Comment by getardretard** [comment]
Hi, thank you for taking the time to respond. I'm not sure that the position data as strings is an issue, I've been using the same czml/json format for years and never had a problem.

The error I am getting is (in chrome):
![2018-03-27 10_32_50-geoapp_chrome error](https://user-images.githubusercontent.com/15369849/37939002-60202038-31ac-11e8-92f0-26a7daa32c54.jpg)

(in firefox):
![2018-03-27 10_32_50-geoapp_firefox error](https://user-images.githubusercontent.com/15369849/37939024-7dca8902-31ac-11e8-9265-0462c998559a.jpg)

and the code it is bombing out on appears to be:
![2018-03-27 10_36_23-developer tools](https://user-images.githubusercontent.com/15369849/37939036-8d88aacc-31ac-11e8-8eca-c335b2a4ae91.jpg)

Which appears to be with the material rendering.

In Cesium 1.42 it works fine, but in Cesium 1.43 it bombs out. (note it bombs out at the 1st animation which is after "15 minutes").

Here is the simplest czml file that produces the error. (after the clock moves past 15 minutes). I've even formatted the position as a number, but it still fails.

Cheers.

```json
[
    {
        "version": "1.0",
        "id": "document"
    },
    {
        "availability": "2018-02-14T04:00:00+1100/2018-02-14T04:15:00+1100",
        "polygon": {
            "extrudedHeight": 1,
            "perPositionHeight": 1,
            "positions": {
                "cartographicDegrees": [
                    145.286799000,
                    -37.998096700,
                    434.513274336283,
                    145.287571746,
                    -37.997967044,
                    434.513274336283,
                    145.288210878,
                    -37.997600495,
                    434.513274336283,
                    145.288605883,
                    -37.997060433,
                    434.513274336283,
                    145.288688461,
                    -37.996440239,
                    434.513274336283,
                    145.288444335,
                    -37.995847150,
                    434.513274336283,
                    145.287915715,
                    -37.995383717,
                    434.513274336283,
                    145.287194005,
                    -37.995130072,
                    434.513274336283,
                    145.286403995,
                    -37.995130072,
                    434.513274336283,
                    145.285682285,
                    -37.995383717,
                    434.513274336283,
                    145.285153665,
                    -37.995847150,
                    434.513274336283,
                    145.284909539,
                    -37.996440239,
                    434.513274336283,
                    145.284992117,
                    -37.997060433,
                    434.513274336283,
                    145.285387122,
                    -37.997600495,
                    434.513274336283,
                    145.286026254,
                    -37.997967044,
                    434.513274336283,
                    145.286799000,
                    -37.998096700,
                    434.513274336283
                ]
            },
            "material": {
                "solidColor": {
                    "color": {
                        "rgba": [
                            "2018-02-14T04:00:00+1100",
                            0,
                            255,
                            0,
                            255,
                            "2018-02-14T04:15:00+1100",
                            0,
                            255,
                            0,
                            255
                        ]
                    }
                }
            }
        },
        "id": "H - 2018-02-14T04:00:00+1100",
        "description": ""
    },
       {
        "availability": "2018-02-14T04:15:00+1100/2018-02-14T04:30:00+1100",
        "polygon": {
            "extrudedHeight": 1,
            "perPositionHeight": 1,
            "positions": {
                "cartographicDegrees": [
                    145.286799000,
                    -37.998096700,
                    335.524652338812,
                    145.287571746,
                    -37.997967044,
                    335.524652338812,
                    145.288210878,
                    -37.997600495,
                    335.524652338812,
                    145.288605883,
                    -37.997060433,
                    335.524652338812,
                    145.288688461,
                    -37.996440239,
                    335.524652338812,
                    145.288444335,
                    -37.995847150,
                    335.524652338812,
                    145.287915715,
                    -37.995383717,
                    335.524652338812,
                    145.287194005,
                    -37.995130072,
                    335.524652338812,
                    145.286403995,
                    -37.995130072,
                    335.524652338812,
                    145.285682285,
                    -37.995383717,
                    335.524652338812,
                    145.285153665,
                    -37.995847150,
                    335.524652338812,
                    145.284909539,
                    -37.996440239,
                    335.524652338812,
                    145.284992117,
                    -37.997060433,
                    335.524652338812,
                    145.285387122,
                    -37.997600495,
                    335.524652338812,
                    145.286026254,
                    -37.997967044,
                    335.524652338812,
                    145.286799000,
                    -37.998096700,
                    335.524652338812
                ]
            },
            "material": {
                "solidColor": {
                    "color": {
                        "rgba": [
                            "2018-02-14T04:15:00+1100",
                            0,
                            255,
                            0,
                            255,
                            "2018-02-14T04:30:00+1100",
                            0,
                            255,
                            0,
                            255
                        ]
                    }
                }
            }
        },
        "id": "H - 2018-02-14T04:15:00+1100",
        "description": ""
    }
]
```

**Comment by hpinkos** [comment]
Thanks @gezonthenet, this is a regression related to some recent changes I made.  I'm looking into this now and should have a fix in for the next release
