### ISSUE TITLE
Draco glTF models broken in Edge

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6540]
They don't work in IE11, but were supposed to work in Edge.  Show stopper?

**Comment by hpinkos** [comment]
```
RuntimeError: Failed to load model: ../../SampleData/models/DracoCompressed/CesiumMilkTruck.gltf
Memory index is out of range
Error
   at RuntimeError (http://localhost:8080/Source/Core/RuntimeError.js:42:13)
   at Anonymous function (http://localhost:8080/Source/Scene/Model.js:1376:13)
   at Anonymous function (http://localhost:8080/Source/ThirdParty/when.js:217:5)
   at Anonymous function (http://localhost:8080/Source/ThirdParty/when.js:297:5)
   at processQueue (http://localhost:8080/Source/ThirdParty/when.js:647:4)
   at _resolve (http://localhost:8080/Source/ThirdParty/when.js:333:4)
   at promiseReject (http://localhost:8080/Source/ThirdParty/when.js:366:4)
   at Anonymous function (http://localhost:8080/Source/ThirdParty/when.js:217:5)
   at Anonymous function (http://localhost:8080/Source/ThirdParty/when.js:297:5)
   at processQueue (http://localhost:8080/Source/ThirdParty/when.js:647:4)
```

**Comment by mramato** [comment]
@ggetz can you please provide a quick triage as to whether this will be a trivial fix?  If not, I'm going to push it until the next release.
