### ISSUE TITLE
Crash in ImageryLayer._createTileImagerySkeletons

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6562]
I'm getting a crash with the following callstack when using a custom terrain and imagery together.  (Both terrain and imagery work fine independently.)

```
DeveloperError: Expected rectangle to be typeof object, actual typeof was undefined
Error
    at new DeveloperError (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:540:19)
    at Object.Check.typeOf.object (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:727:19)
    at Function.Rectangle.southwest (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:6816:30)
    at WebMercatorTilingScheme.rectangleToNativeRectangle (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:85259:54)
    at ImageryLayer._createTileImagerySkeletons (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:208363:33)
    at prepareNewTile (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:207141:23)
    at Function.GlobeSurfaceTile.processStateMachine (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:207045:13)
    at GlobeSurfaceTileProvider.loadTile (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:209507:26)
    at processSinglePriorityLoadQueue (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:212341:26)
    at processTileLoadQueue (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:212332:9)
```

And here's the code to reproduce this (I can't share the data publicly, so I didn't provide the access token or ids.  Contact me directly for the data.

```js
var viewer = new Cesium.Viewer('cesiumContainer',{
    terrainProvider : new Cesium.CesiumTerrainProvider({
        url: Cesium.IonResource.fromAssetId('See me')
    }),
    imageryProvider: false,
    baseLayerPicker: false
});


var imageryLayer = viewer.imageryLayers.addImageryProvider(
    new Cesium.IonImageryProvider({ assetId: 'See me' })
);

viewer.zoomTo(imageryLayer)
    .otherwise(function (error) {
        console.log(error);
    });
```

The problem does not happen if I enable a global imagery base layer (as long as that layer is turned on).  Adding a global imagery base layer with show = false still reproduces the issue.

**Comment by mramato** [comment]
This was pre-imagery/terrain overhaul (and for some reason I didn't include enough info to try and reproduce this).
