### ISSUE TITLE
Crash when picking and switching terrain provider

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#6916]
Can be a pain to reproduce because it only happens sometimes, but here are the steps:
- wait for globe to load ellipsoid terrain
- click `Enable Terrain` button and immediately move the mouse
- `scene.pick` causes a crash.  We're executing some kind of command that is already destroyed.

```js
var viewer = new Cesium.Viewer('cesiumContainer');

var hpr = new Cesium.HeadingPitchRange(0, -0.5, 5000);
var scene = viewer.scene;

var handler = new Cesium.ScreenSpaceEventHandler(scene.canvas);
handler.setInputAction(function(movement) {
    var pickedObject = scene.pick(movement.endPosition);
}, Cesium.ScreenSpaceEventType.MOUSE_MOVE);

viewer.camera.lookAt(Cesium.Cartesian3.fromDegrees(-90.5974899906479, 32.03876681766648, 85), hpr);

Sandcastle.addToolbarButton('Enable Terrain', function() {
    viewer.terrainProvider = Cesium.createWorldTerrain();
});
```

```
Sandcastle-client.js:120 Uncaught DeveloperError: This object was destroyed, i.e., destroy() was called.
Error
    at new DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:43:19)
    at VertexArray.throwOnDestroyed (http://localhost:8080/Source/Core/destroyObject.js:45:19)
    at continueDraw (http://localhost:8080/Source/Renderer/Context.js:997:12)
    at Context.draw (http://localhost:8080/Source/Renderer/Context.js:1034:9)
    at DrawCommand.execute (http://localhost:8080/Source/Renderer/DrawCommand.js:523:17)
    at executeCommand (http://localhost:8080/Source/Scene/Scene.js:2075:25)
    at executeCommands (http://localhost:8080/Source/Scene/Scene.js:2285:17)
    at executeCommandsInViewport (http://localhost:8080/Source/Scene/Scene.js:2852:9)
    at updateAndExecuteCommands (http://localhost:8080/Source/Scene/Scene.js:2700:13)
    at Scene.pick (http://localhost:8080/Source/Scene/Scene.js:3531:9)
```

**Comment by hpinkos** [comment]
@bagnell any ideas here?
