### ISSUE TITLE
Crash switching scene modes

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#6929]
Run http://localhost:8080/Apps/Sandcastle/index.html?src=Labels.html and continually switch between 2D/3D mode (no need to do anything else), you will randomly crash:

```
DeveloperError: normalized result is not a number
Error
    at new DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:43:19)
    at Function.Cartesian3.normalize (http://localhost:8080/Source/Core/Cartesian3.js:421:19)
    at Ellipsoid.geodeticSurfaceNormal (http://localhost:8080/Source/Core/Ellipsoid.js:368:27)
    at Ellipsoid.cartesianToCartographic (http://localhost:8080/Source/Core/Ellipsoid.js:458:22)
    at updateMembers (http://localhost:8080/Source/Scene/Camera.js:573:77)
    at Camera.get (http://localhost:8080/Source/Scene/Camera.js:760:17)
    at Camera._updateCameraChanged (http://localhost:8080/Source/Scene/Camera.js:340:69)
    at Scene.initializeFrame (http://localhost:8080/Source/Scene/Scene.js:3172:22)
    at CesiumWidget.render (http://localhost:8080/Source/Widgets/CesiumWidget/CesiumWidget.js:692:25)
    at render (http://localhost:8080/Source/Widgets/CesiumWidget/CesiumWidget.js:69:32)
```

@bagnell any ideas?

**Comment by mramato** [comment]
We're always in the middle of a morph when the crash happens and the camera position looks like it's at least partially NaN

**Comment by ggetz** [comment]
This issue is marked for next release, so we should try to get in a fix for next week. Who would be best to look at this? @bagnell?

**Comment by mramato** [comment]
Yes, @bagnell
