### ISSUE TITLE
Polygon Intervals and Availability broken in IE

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#7103]
http://localhost:8080/Apps/Sandcastle/?src=CZML%20Polygon%20-%20Intervals%2C%20Availability.html&label=CZML

This works in 1.45 but not in 1.46

```
TypeError: Unable to get property '_target' of undefined or null reference
TypeError: Unable to get property '_target' of undefined or null reference
   at UniformSampler.prototype.set (https://cesiumjs.org/releases/1.46/Source/Renderer/createUniform.js:198:9)
   at ShaderProgram.prototype._setUniforms (https://cesiumjs.org/releases/1.46/Source/Renderer/ShaderProgram.js:501:13)
   at continueDraw (https://cesiumjs.org/releases/1.46/Source/Renderer/Context.js:1000:9)
   at Context.prototype.draw (https://cesiumjs.org/releases/1.46/Source/Renderer/Context.js:1036:9)
   at DrawCommand.prototype.execute (https://cesiumjs.org/releases/1.46/Source/Renderer/DrawCommand.js:502:9)
   at executeCommand (https://cesiumjs.org/releases/1.46/Source/Scene/Scene.js:2069:13)
   at executeCommands (https://cesiumjs.org/releases/1.46/Source/Scene/Scene.js:2259:17)
   at executeCommandsInViewport (https://cesiumjs.org/releases/1.46/Source/Scene/Scene.js:2756:9)
   at updateAndExecuteCommands (https://cesiumjs.org/releases/1.46/Source/Scene/Scene.js:2604:13)
   at render (https://cesiumjs.org/releases/1.46/Source/Scene/Scene.js:3163:9)
```

Related: A bunch of these tests are failing with the same error message: http://localhost:8080/Specs/SpecRunner.html?spec=DataSources%2FGeometryVisualizer

**Comment by hpinkos** [comment]
Marking this `Next Release` because it's a regression.  We really should have caught this before now...

**Comment by hpinkos** [comment]
@likangning93 this seems to have broken with your Materials on Ground Primitives PR

**Comment by lilleyse** [comment]
Looking into this closer, this seems to happen when

1. Depth textures aren't supported
2. Ground primitives are batched

When ground primitives are batched they derive texture coordinates from reading `czm_globeDepthTexture` which is not defined if depth textures aren't supported.

Either the ground primitives shouldn't be trying to draw themselves at all. Or they shouldn't be batched.

@likangning93 do you know if this might be a quick fix?

**Comment by likangning93** [comment]
I'll take a look

**Comment by likangning93** [comment]
@hpinkos sorry must have slipped my inbox somehow...
