### ISSUE TITLE
Crash after adding clipping plane to empty clipping plane collection

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#7167]
Cesium crashes when adding a clipping plane to an empty clipping plane collection. It does not crash if the collection already has at least one plane in it. Seems to affect all the different types of objects that clipping planes can be applied to.

[Model Example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=fVRRb9owEP4rES8EKXPCoO1GaTVGJ+1hU1lB6wvSZOKDWHPsyHbo2NT/vrOdQGDSIgT23Xff3X13YU91tOfwAjq6iyS8RHMwvC7Jd2+L+7m/zpW0lEvQ/ST6s5YRPiYHCaOHRykOk8jqGpJgt6A1Qhda7TkDPWkJcw3UwrPSgq0CJB6s5evgdi33WMNOqA1gCaEW4tmJNyLA/xIGlS1WYOxsh9HGNjQY5NIjLDDlglcVl7uFoBLMeVfzrm+uhIDcciXjpidgO3jmzBbRJBqSrCkv0FbKcIdFwpaMaosnKkdkq1X5ADsNYOI3w7cjkt2Mx9fD90k0HpPsKhvdZNdJNMyyjGRtxwVQhqWc+L5SWxCrntBMpYmHo6sTuOI2LxCK8Y1FY/VnhqK6GOHnkGDhQp8QHTcZk8CWeIo2gdIccMbnHa40FrJVujSkuCD7VuM0tXTitcokroSWD8m4PZwG6u8cDKGMtXIfJZ0cj80SdauZdG+Nv1QMBHoaIvfUmqOhT0h6/MyqyqRLWlYCHqilqY8yaWhuxnVz+oFHXLVNPzmxmZwKQL53HVvJJS/rcsF/gVjy3849dAPtQC52b3JhCMDX014Fbaym+U9gn1rJgnYesaSS5dRYAU64lVJiQ/XH2lrUvT9jLKocMb6V21qGVR60ovi1cd7/vAJx13Fc5xh3P3Gb5b8G4fs2sJ435Kfpkzi/76qX9KbGHgTch4APvKyUtjgfEeNMLOA4cHVMuqmxaUtyY1zYNG2DpozvI87u1r2L/551D7NTY9CzrYUfwbp3P00RfxYmlF/Vxz1oQQ8OUgzvvwQjIWSa4vXfKBu07TD+BQ)
[3D Tiles Example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=fVLBauMwEP0V4UtsCHJKyi6kbmg2vRQKLa3ZXnxRrEkiVpaMNHZJl/77jiVnSbJLfZCsmfdm3jypF471Ct7BsVtm4J2twauu4T9DLJ3U4bi2BoUy4CZT9rsyjD5fg4H5/ZPRhwVD18E0xhGcI+izs72S4BbHgrUDgfBmnZZlhKRZZT6zm8r0pGGn7QZIQtTCQ3UeggQIO5fQ4r4Ej6sdsT2OZYg0tCdYrFRr1bbK7J61MODPp1qf5tZWa6hRWZOOM4HcwZuSuGcLdsVno7xYFpUGD3gpsXWqUah68FxImZ72Ctv8vozEY4/O6b+ePFjzAt52rga+dbZZeQI+yPTb7Pt1Nvp5Mc7iIjBoHEVGWR/WNqVNR7kx9SqMrIVHDYPI0lq9Ee5Hh0ijT1ZSsnaoRXe77Uw0JDte8zB6yH5h5NnUwiH9CTNPycEpm41LFteb/w0VnAtNhnzwPJkmhceDhmUk3KmmtQ4H91LOc4SG8NQo33T1L0Beez/QivxIKqTqmZK3VXLxgquEugvvKbPttH5VH1AlyyIn/BlNWyFJ4VMPTovDANlfLR9jkHNe5HT8l4XR25OKfwA)
[Terrain example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=nVTfb9owEP5XLF4IEnMCtJRSWo2xStu0atVA6wvSZOIDrDp2ZDtQNvV/39lJ+NGhPSzKg3333fnuu8/eMEM2ArZgyC1RsCUTsKLI6I9gi5pp2E60ckwoMM02+T1XBD/7vBu7TNt8DQaGZMmkhXblWutC8rESGXNAhsSZonY5MAYTPRq9ERzMsD4uNYDYJ20kn5WQqDVXr62budpghSupF4AFlpVSm4ICGowIKCG5tsIJrRBV5Zww43DFVI8ujc6+M45rG73r0mTQ715fXV9c9XqXne6g3yYJ7V8O+v1uknR6Sa/f6V+0SeciSWjS2p8Aygm3O1QR9gIsZZxHFSv7Kob7ZdX5Qr+gsYL5j4sMlEWARfsR84eyo7KCupI26Q5CRe1DEs+wEUySPZMTLbWhT58+z+7pVrj1WOZrFiW0dxymCydxnKezOXKEJGdzltDXajZIzP9wkWkO8pSNwgg0NCmN9/84z208ZVku4SNzLA5RNi5remCqWv3EJWph0TymRaD4iuxRvICcil++UZzzCW8vHjBNmfRO5PVtY0FdlEPu1jOwbrxCTVpXiRNF4Im7qWGpFHku1OpRMgX29CZNjn3IpITUU1GzFLp6YM4Ir49SYzTVWV44eDj4oirbl0KiNJAPoEpvo1Y9VeCrcmrnh3Y6LWdY+gz8vhZ0eWpATJniKbNOgh/lTGu5YOZD4RxW3BxzTnLfBj4Dy0KVfbTqMYZb6L3/6D86L3TS8fImQeRB4eTdVX35fOpzLAephfM8KjTYaDdG1u0k3JVh70WWa+NQXDJCQTlALSFzNl4U2L+jqbU+bBTXQSMuNkTw23njzbs3b5BUMmvRsyxk0NS8cTeKEX8SJjW+Mmr1bQNGsp2HrDt3X0sjpXQU4/bvKFfSfJTxDw)
[Point Cloud Example](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=fVLBauMwEP0V4UtsCHJDuiykbmg2vRQKLa3ZXnxRrEkiVpaMNHZJl/77jiVnSbJLfZCsmfdm3jypF471Ct7BsVtm4J2twauu4T9DLJ3U4bi2BoUy4CZT9rsyjD5fg4H5/ZPRhwVD18E0xhGcI+izs72S4BbHgrUDgfBmnZZlhKRZZT6zm8r0pGGn7QZIQtTCQ3UeggQIO5fQ4r4Ej6sdsT2OZYg0tCdYrFRr1bbK7J61MODPp1qf5tZWa6hRWZOOM4HcwZuSuGcLNuNXo7xYFpUGD3gpsXWqUah68FxImZ72Ctv8vozEY4/O6b+ePFjzAt52rga+dbZZeQI+yPTb99l1Nvp5Mc7iIjBoHEVGWR/WNqVNR7kx9SqMrIVHDYPI0lq9Ee5Hh0ijT1ZSsnaoRXe77Uw0JDte8zB6yH5h5NnUwiH9CTNPycEpuxqXLK43/xsqOBeaDPngeTJNCo8HDctIuFNNax0O7qWc5wgN4alRvunqX4C89n6gFfmRVEjVMyVvq+TiBVcJdRfeU2bbaf2qPqBKlkVO+DOatkKSwqcenBaHAbKfLR9jkHNe5HT8l4XR25OKfwA)

```
RuntimeError: Fragment shader failed to compile.  Compile log: ERROR: 0:24: 'NaN' : undeclared identifier
ERROR: 0:24: '.0' : syntax error

Error
    at new RuntimeError (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:4365:19)
    at createAndLinkProgram (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:100439:23)
    at initialize (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:100660:23)
    at ShaderProgram._bind (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:100677:9)
    at beginDraw (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:175514:23)
    at Context.draw (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:175576:9)
    at DrawCommand.execute (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:96653:17)
    at executeCommand (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:239176:21)
    at executeCommands (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:239555:17)
    at executeCommandsInViewport (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:239968:9)
```

**Comment by lilleyse** [comment]
@OmarShehata could you investigate this?

**Comment by OmarShehata** [comment]
I'm taking a look now.
