### ISSUE TITLE
FreezeFrame of viewerCesium3DTilesInspectorMixin occasionally causes crash

### ISSUE THREAD

**Issue by loshjawrence** [AnalyticalGraphicsInc/cesium#7256]
@loshjawrence 
Failure message:
```
An error occurred while rendering. Rendering has stopped.
DeveloperError: This object was destroyed, i.e., destroy() was called.
Error
    at new DeveloperError (http://localhost:8080/Source/Core/DeveloperError.js:43:19)
    at VertexArray.throwOnDestroyed (http://localhost:8080/Source/Core/destroyObject.js:45:19)
    at continueDraw (http://localhost:8080/Source/Renderer/Context.js:1032:12)
    at Context.draw (http://localhost:8080/Source/Renderer/Context.js:1069:9)
    at DrawCommand.execute (http://localhost:8080/Source/Renderer/DrawCommand.js:538:17)
    at executeCommand (http://localhost:8080/Source/Scene/Scene.js:1875:21)
    at executeCommands (http://localhost:8080/Source/Scene/Scene.js:2139:21)
    at executeCommandsInViewport (http://localhost:8080/Source/Scene/Scene.js:2667:9)
    at updateAndExecuteCommands (http://localhost:8080/Source/Scene/Scene.js:2460:13)
    at render (http://localhost:8080/Source/Scene/Scene.js:3075:9)
```
Example Sandcastle:
anything with a pickable 3dtileset

**Comment by hpinkos** [comment]
duplicate #7680
