### ISSUE TITLE
different behavior in develop and production.

### ISSUE THREAD

**Issue by ohadmanor** [AnalyticalGraphicsInc/cesium#7355]
Hi,

I'm using cesium 1.51 with the latest chrome.

when I'm running with VS everything work fine but when I'm publish and running it on the same machine I get the following error:

An error occurred while rendering. Rendering has stopped.
RuntimeError: Fragment shader failed to compile.  Compile log: 
Error
    at new t (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:444:24436)
    at f (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:467:13646)
    at y (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:467:16063)
    at d._bind (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:467:17078)
    at U (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:495:18642)
    at B.draw (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:495:22808)
    at n.execute (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:466:17282)
    at Ne (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:518:23499)
    at He (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:518:24994)
    at Ke (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:519:1831)

I play around with chrome webGL configuration (enable WebGL Draft Extensions) and I started to get that error:

RangeError: Invalid array length
RangeError: Invalid array length
    at w (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:518:8009)
    at S.createPotentiallyVisibleSet (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:518:11114)
    at Ke (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:519:1762)
    at Xe (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:518:30980)
    at st (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:519:8307)
    at lt (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:519:8494)
    at Ee.render (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:519:18812)
    at x.render (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:525:28322)
    at t (http://localhost:5100/lib/Cesium-1.51/Build/Cesium/Cesium.js:525:21731)

**Comment by ohadmanor** [comment]
I found the problem . . . .

Sorry
