### ISSUE TITLE
Post processing examples broken.

### ISSUE THREAD

**Issue by mramato** [AnalyticalGraphicsInc/cesium#7367]
Works in 1.51 so this is a show stopper.  CC @bagnell @lilleyse 

Select Mouse-over Silhouette
http://localhost:8080/Apps/Sandcastle/index.html?src=Per-Feature%20Post%20Processing.html&label=All

Doesn't work in Chrome/Firefox in Windows or Linux.

Chrome:

```
TypeError: Cannot set property 'czm_aces' of undefined
TypeError: Cannot set property 'czm_aces' of undefined
    at getCompositeDependencies (http://localhost:8080/Source/Scene/PostProcessStageTextureCache.js:114:56)
    at getDependencies (http://localhost:8080/Source/Scene/PostProcessStageTextureCache.js:133:28)
    at createFramebuffers (http://localhost:8080/Source/Scene/PostProcessStageTextureCache.js:201:28)
    at PostProcessStageTextureCache.update (http://localhost:8080/Source/Scene/PostProcessStageTextureCache.js:288:13)
    at PostProcessStageCollection.update (http://localhost:8080/Source/Scene/PostProcessStageCollection.js:647:28)
    at updateAndClearFramebuffers (http://localhost:8080/Source/Scene/Scene.js:2963:25)
    at executeCommandsInViewport (http://localhost:8080/Source/Scene/Scene.js:2757:17)
    at updateAndExecuteCommands (http://localhost:8080/Source/Scene/Scene.js:2558:13)
    at render (http://localhost:8080/Source/Scene/Scene.js:3183:9)
    at tryAndCatchError (http://localhost:8080/Source/Scene/Scene.js:3203:13)
```

Firefox
```
TypeError: dependencies[name] is undefined getCompositeDependencies@http://localhost:8080/Source/Scene/PostProcessStageTextureCache.js:114:17 getDependencies@http://localhost:8080/Source/Scene/PostProcessStageTextureCache.js:133:28 createFramebuffers@http://localhost:8080/Source/Scene/PostProcessStageTextureCache.js:201:28 PostProcessStageTextureCache.prototype.update@http://localhost:8080/Source/Scene/PostProcessStageTextureCache.js:288:13 PostProcessStageCollection.prototype.update@http://localhost:8080/Source/Scene/PostProcessStageCollection.js:647:9 updateAndClearFramebuffers@http://localhost:8080/Source/Scene/Scene.js:2963:13 executeCommandsInViewport@http://localhost:8080/Source/Scene/Scene.js:2757:17 updateAndExecuteCommands@http://localhost:8080/Source/Scene/Scene.js:2558:13 render@http://localhost:8080/Source/Scene/Scene.js:3183:9 tryAndCatchError@http://localhost:8080/Source/Scene/Scene.js:3203:13 Scene.prototype.render@http://localhost:8080/Source/Scene/Scene.js:3252:13 CesiumWidget.prototype.render@http://localhost:8080/Source/Widgets/CesiumWidget/CesiumWidget.js:694:13 render@http://localhost:8080/Source/Widgets/CesiumWidget/CesiumWidget.js:69:25
```

**Comment by mramato** [comment]
Post processing example too: http://localhost:8080/Apps/Sandcastle/index.html?src=Post%20Processing.html&label=All
