### ISSUE TITLE
Test failures in Chrome 71

### ISSUE THREAD

**Issue by shunter** [AnalyticalGraphicsInc/cesium#7388]
Tests are failing on Chrome 71 which just went stable in the last day or so.  I re-ran the build for the head of master which was passing before on 70 and now failing.

https://travis-ci.org/AnalyticalGraphicsInc/cesium/jobs/463025106

 Core/Resource
    fetchImage
      ✗ Calls loadWithXhr with blob response type if headers is set
	Error: Failed: promise rejected: [object Event]
	    at <Jasmine>
	    at Specs/customizeJasmine.js:80:26
	    at Promise.then (Source/ThirdParty/when.js:217:33)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
    loadWithXhr
      data URI loading
        ✗ can load Base64 encoded data as blob
	Error: Failed: promise rejected: [object Event]
	    at <Jasmine>
	    at Specs/customizeJasmine.js:80:26
	    at Promise.then (Source/ThirdParty/when.js:217:33)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
  Core/loadImageFromTypedArray
    ✗ can load an image
	Error: Failed: promise rejected: [object Event]
	    at <Jasmine>
	    at Specs/customizeJasmine.js:80:26
	    at Promise.then (Source/ThirdParty/when.js:217:33)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
  Scene/ArcGisMapServerImageryProvider
    ✗ supports tiled servers in web mercator projection
	Error: Failed: promise rejected: [object Event]
	    at <Jasmine>
	    at Specs/customizeJasmine.js:80:26
	    at Promise.then (Source/ThirdParty/when.js:217:33)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
    ✗ supports tiled servers in geographic projection
	Error: Failed: promise rejected: [object Event]
	    at <Jasmine>
	    at Specs/customizeJasmine.js:80:26
	    at Promise.then (Source/ThirdParty/when.js:217:33)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
    ✗ includes security token in requests if one is specified
	Error: Failed: promise rejected: [object Event]
	    at <Jasmine>
	    at Specs/customizeJasmine.js:80:26
	    at Promise.then (Source/ThirdParty/when.js:217:33)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
  Scene/BingMapsImageryProvider
    ✗ can provide a root tile
	Error: Failed: promise rejected: [object Event]
	    at <Jasmine>
	    at Specs/customizeJasmine.js:80:26
	    at Promise.then (Source/ThirdParty/when.js:217:33)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
    ✗ sets correct culture in tile requests
	Error: Failed: promise rejected: [object Event]
	    at <Jasmine>
	    at Specs/customizeJasmine.js:80:26
	    at Promise.then (Source/ThirdParty/when.js:217:33)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
    ✗ raises error event when image cannot be loaded
	Error: Timeout - Async callback was not invoked within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
	    at <Jasmine>
  Scene/DiscardMissingTileImagePolicy
    shouldDiscardImage
      ✗ discards an image that is identical to the missing image
	Error: Expected false to equal true.
	    at <Jasmine>
	    at Specs/Scene/DiscardMissingTileImagePolicySpec.js:91:61
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
      ✗ discards an image that is identical to the missing image even if the missing image is transparent
	Error: Expected false to equal true.
	    at <Jasmine>
	    at Specs/Scene/DiscardMissingTileImagePolicySpec.js:113:69
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
  Scene/GoogleEarthEnterpriseImageryProvider
    ✗ can provide a root tile
	Error: Failed: promise rejected: [object Event]
	    at <Jasmine>
	    at Specs/customizeJasmine.js:80:26
	    at Promise.then (Source/ThirdParty/when.js:217:33)
	    at Source/ThirdParty/when.js:297:13
	    at processQueue (Source/ThirdParty/when.js:647:4)
    ✗ raises error event when image cannot be loaded
	Error: Timeout - Async callback was not invoked within 5000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)
	    at <Jasmine>
  Scene/Batched3DModel3DTileContent
    ✗ gets memory usage
	Error: Expected 0 to equal 65536.
	    at <Jasmine>
	    at Specs/Scene/Batched3DModel3DTileContentSpec.js:254:48
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
	Error: Expected 0 to equal 65536.
	    at <Jasmine>
	    at Specs/Scene/Batched3DModel3DTileContentSpec.js:261:48
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
	Error: Expected 0 to equal 40.
	    at <Jasmine>
	    at Specs/Scene/Batched3DModel3DTileContentSpec.js:262:50
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
	Error: Expected 0 to equal 65536.
	    at <Jasmine>
	    at Specs/Scene/Batched3DModel3DTileContentSpec.js:267:48
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
	Error: Expected 0 to equal 80.
	    at <Jasmine>
	    at Specs/Scene/Batched3DModel3DTileContentSpec.js:268:50
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
  Scene/Cesium3DTileset
    ✗ verify memory usage statistics for shared resources
	Error: Expected 840 to be 4200.
	    at <Jasmine>
	    at Specs/Scene/Cesium3DTilesetSpec.js:808:51
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
	Error: Expected 65536 to be 327680.
	    at <Jasmine>
	    at Specs/Scene/Cesium3DTilesetSpec.js:809:51
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
    ✗ clipping planes cull tiles completely inside clipping region for i3dm
	Error: Expected 2 to equal 6.
	    at <Jasmine>
	    at Specs/Scene/Cesium3DTilesetSpec.js:3253:49
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
	Error: Expected 2 to equal 6.
	    at <Jasmine>
	    at Specs/Scene/Cesium3DTilesetSpec.js:3269:49
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
	Error: Expected 2 to equal 6.
	    at <Jasmine>
	    at Specs/Scene/Cesium3DTilesetSpec.js:3277:49
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
  Scene/Instanced3DModel3DTileContent
    ✗ gets memory usage
	Error: Expected 0 to equal 65536.
	    at <Jasmine>
	    at Specs/Scene/Instanced3DModel3DTileContentSpec.js:278:48
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
	Error: Expected 0 to equal 65536.
	    at <Jasmine>
	    at Specs/Scene/Instanced3DModel3DTileContentSpec.js:285:48
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
	Error: Expected 0 to equal 100.
	    at <Jasmine>
	    at Specs/Scene/Instanced3DModel3DTileContentSpec.js:286:50
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
	Error: Expected 0 to equal 65536.
	    at <Jasmine>
	    at Specs/Scene/Instanced3DModel3DTileContentSpec.js:291:48
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793
	Error: Expected 0 to equal 200.
	    at <Jasmine>
	    at Specs/Scene/Instanced3DModel3DTileContentSpec.js:292:50
	    at r.then (Build/Cesium/Cesium.js:444:7236)
	    at Build/Cesium/Cesium.js:444:7793

**Comment by mramato** [comment]
There were some CORS changes that might be affecting things here.  Might be obvious looking at the network tab in the debugger.

**Comment by shunter** [comment]
It only happens in headless.  Eventually I remembered this: #7292 

Basically Blobs are broken in headless 71.  No recent activity in the Chrome issue.  https://crbug.com/902918

Not sure what you want to do.  Lock tests to 70 until something happens?

**Comment by mramato** [comment]
Travis makes that easy to do, so it might be our best option in the short term if there's not an easy workaround.

**Comment by mramato** [comment]
Actually, travis has no way to lock Chrome versions, you can either pick `stable` or `beta`, unless we do use a Docker image or something, we don't have a lot of options.

**Comment by mramato** [comment]
We could also just go all Firefox until it's fixed.  Almost all of us run Chrome on the desktop so it's unlikely a Chrome-only bug will slip in anytime soon.

**Comment by mramato** [comment]
Offending tests were ignored in #7392, we can re-enable them once the linked crbug is fixed.

**Comment by mramato** [comment]
We turned Chrome back on in #8069
