### ISSUE TITLE
Polygons using rhumb lines crash when point on IDL is specified

### ISSUE THREAD

**Issue by shehzan10** [AnalyticalGraphicsInc/cesium#7550]
Sandcastle to reproduce:
```
var viewer = new Cesium.Viewer('cesiumContainer');

var purplePolygonUsingRhumbLines = viewer.entities.add({
    name : 'Purple polygon using rhumb lines',
    polygon : {
        hierarchy : [
            Cesium.Cartesian3.fromDegrees(179, 10),
            Cesium.Cartesian3.fromDegrees(180, 10), // works if commented out
            Cesium.Cartesian3.fromDegrees(-179, 10),
            Cesium.Cartesian3.fromDegrees(-179, 11),
            Cesium.Cartesian3.fromDegrees(180, 11), // works if commented out
            Cesium.Cartesian3.fromDegrees(179, 11)
        ],
        material : Cesium.Color.PURPLE,
        arcType : Cesium.ArcType.RHUMB
    }
});

viewer.zoomTo(viewer.entities);
```

Here's the stacktrace:
```
An error occurred while rendering.  Rendering has stopped.
undefined
DeveloperError: normalized result is not a number
Error
    at new DeveloperError (http://localhost:8004/Source/Core/DeveloperError.js:43:19)
    at Function.Cartesian3.normalize (http://localhost:8004/Source/Core/Cartesian3.js:421:19)
    at computeTriangleAttributes (http://localhost:8004/Source/Core/GeometryPipeline.js:2003:28)
    at splitLongitudeTriangles (http://localhost:8004/Source/Core/GeometryPipeline.js:2160:21)
    at Object.GeometryPipeline.splitLongitude (http://localhost:8004/Source/Core/GeometryPipeline.js:2630:17)
    at geometryPipeline (http://localhost:8004/Source/Scene/PrimitivePipeline.js:138:38)
    at Object.PrimitivePipeline.combineGeometry (http://localhost:8004/Source/Scene/PrimitivePipeline.js:284:26)
    at combineGeometry (http://localhost:8004/Source/Workers/combineGeometry.js:11:41)
    at callAndWrap (http://localhost:8004/Source/Workers/createTaskProcessorWorker.js:20:31)
    at http://localhost:8004/Source/Workers/createTaskProcessorWorker.js:66:25
```

From limited debugging, it looks like `coords` is becoming `NaN` because 2 of the points are epsilon equal to each other. (https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/GeometryPipeline.js#L1964-L1967)

```
p0 => Cartesian3 {x: -6290017.132807267, y: -109792.65745275143, z: 1101853.5551215778}
p1 => Cartesian3 {x: -6290975.278813254, y: 7.704222738713778e-10, z: 1101853.5551215776}
p2 => Cartesian3 {x: -6290975.278813254, y: 7.704222738713778e-10, z: 1101853.5551215773}
coords => Cartesian3 {x: NaN, y: NaN, z: NaN}
```

My initial guess was that during subdivision, a points on IDL was getting added right at the intermediate points specified, and leading to degenerate triangles.

However this does not seem to be the case. I'm not entirely sure where the points above were added.

**Comment by hpinkos** [comment]
Does this crash with geodesic?  I wouldn't expect the arctype to make a difference by the time it gets to the `splitLongitude` step

**Comment by shehzan10** [comment]
> Does this crash with geodesic? I wouldn't expect the arctype to make a difference by the time it gets to the `splitLongitude` step

No, doesn't crash for geodesic.

With the 180 degree points included it looks like, which is correct:
![image](https://user-images.githubusercontent.com/2288659/52441377-6bc27580-2aee-11e9-9264-57f79ba59671.png)

**Comment by hpinkos** [comment]
No longer crashes
