### ISSUE TITLE
RangeError reported in PolylineGeometryLibrary.subdivideRhumbLine

### ISSUE THREAD

**Issue by GatorScott** [AnalyticalGraphicsInc/cesium#7553]
I'm getting a crash in master trying to display time zones that are in a GeoJSON file.

[ne_10m_time_zones_bug.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/2846330/ne_10m_time_zones_bug.zip)

`RangeError: Invalid array length
RangeError: Invalid array length
    at Object.PolygonGeometryLibrary.subdivideRhumbLine (http://localhost:8080/Source/Core/PolygonGeometryLibrary.js:207:26)
    at createGeometryFromPositions (http://localhost:8080/Source/Core/PolygonOutlineGeometry.js:90:60)
    at Function.PolygonOutlineGeometry.createGeometry (http://localhost:8080/Source/Core/PolygonOutlineGeometry.js:555:36)
    at createPolygonOutlineGeometry (http://localhost:8080/Source/Workers/createPolygonOutlineGeometry.js:16:39)
    at createGeometry (http://localhost:8080/Source/Workers/createGeometry.js:47:40)
    at callAndWrap (http://localhost:8080/Source/Workers/createTaskProcessorWorker.js:20:31)
    at http://localhost:8080/Source/Workers/createTaskProcessorWorker.js:66:25`

Sandcastle example:

`var viewer = new Cesium.Viewer('cesiumContainer');
viewer.dataSources.add(Cesium.GeoJsonDataSource.load('../../SampleData/ne_10m_time_zones_bug.geojson'));
`

Browser:

Chrome Version 72.0.3626.96 (Official Build) (64-bit)

Operating System:

Windows 10

**Comment by hpinkos** [comment]
Thanks @GatorScott 

@shehzan10 can you look into this please?

**Comment by shehzan10** [comment]
I loaded the geojson into QGIS and OSM map (in Web Mercator in the background): 
![image](https://user-images.githubusercontent.com/2288659/52507607-017a0580-2bc0-11e9-978b-1ea1d6228ea5.png)

It certainly looks like the geojson is going all the way to 90 degrees north and south (changing geojson to load in 3857 makes those go to infinity, so confirmed it that way as well).

So the lines that look horizontal at 90 degrees north, are actually the same points in 3D. I think that's why it's crashing.

We do not limit rhumb lines to 89.x degrees in the current code. Maybe we should?

**Comment by shehzan10** [comment]
I just tried some local changes to limit rhumb lines to 89 degrees if both latitude and longitude are at the pole. But that doesn't seem to be stopping the crash.

**Comment by hpinkos** [comment]
Taking a closer look, this geojson example hasn't ever worked in CesiumJS so I'm removing the `next release` label. While it's something we want to fix, it's not as urgent because it wasn't a recent breaking change with the additions of rhumb lines.

**Comment by hpinkos** [comment]
Also reported in https://github.com/CesiumGS/cesium/issues/8599

**Comment by aniledev** [comment]
@hpinkos Has there been any movement on this issue? I'm experiencing the same behavior as @gcure1 in the duplicated issue: https://github.com/CesiumGS/cesium/issues/8599.

I suspect the problematic polygon data in Antarctica is the cause as my data included simliar values with boundaries for Antartica. Changing the adjacent coordinates with -90.0 latitude to -89.9 eliminated the RangeError, but I still encountered a blank globe in Cesium.

Is there a workaround available?
