### ISSUE TITLE
Particle System Sandcastle is crashing

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7617]
Open https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=Particle%20System.html.

Wait 1 second, crash:

```
TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at getCornerFromEdge (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:211181:30)
    at getCorner (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:210885:13)
    at createFillMesh (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:210517:24)
    at propagateEdge (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:210296:17)
    at visitTile (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:210283:9)
    at visitRenderedTiles (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:210222:13)
    at Function.TerrainFillMesh.updateFillTiles (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:210159:13)
    at GlobeSurfaceTileProvider.endUpdate (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:211703:29)
    at QuadtreePrimitive.render (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:214822:26)
    at Globe.render (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:216427:21)
```

Window, Chrome Version 72.0.3626.119 (Official Build) (64-bit).

**Comment by OmarShehata** [comment]
@kring looks like it's a fill tiles crash?

**Comment by hpinkos** [comment]
@OmarShehata I do not see this crash

**Comment by mramato** [comment]
I don't see a crash either

**Comment by emackey** [comment]
It's a dirty cache.  I can reproduce it in a normal window, but I can't reproduce in an Incogneto window.

**Comment by hpinkos** [comment]
Is there anything we can really do about that?

**Comment by emackey** [comment]
It looks like there's a half-hour max-age on various JS files... Not sure I hit the old Sandcastle within half an hour though.  Maybe a race condition?

**Comment by OmarShehata** [comment]
I can confirm clearing cache fixes it. We can just close it, but it's good to know if anyone reports seeing this it's an easy fix.

**Comment by OndroNR** [comment]
Placing new Cesium build to different URL also helps.
