### ISSUE TITLE
Runtime error with gltf 2.0 file without texture

### ISSUE THREAD

**Issue by gunmiosb** [AnalyticalGraphicsInc/cesium#7766]
Using more than one viewer and loading the same gltf 2.0 file without textures on both leads to this error:

```
[Cesium WebGL] Fragment shader compile log: ERROR: 0:? : '' : syntax error

[Cesium WebGL] Fragment shader translation failed.
An error occurred while rendering.  Rendering has stopped.
undefined
RuntimeError: Fragment shader failed to compile.  Compile log: ERROR: 0:? : '' : syntax error

Error
    at new RuntimeError (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:4456:19)
    at createAndLinkProgram (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:95099:23)
    at initialize (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:95320:23)
    at ShaderProgram.get (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:94982:17)
    at getAttributeLocations (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:151990:47)
    at https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:152204:42
    at Function.ForEach.meshPrimitive (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:140447:29)
    at https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:152201:21
    at Function.ForEach.object (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:140257:29)
    at Function.ForEach.topLevel (https://cesiumjs.org/Cesium/Build/CesiumUnminified/Cesium.js:140276:24)
```

The error occurred after updating from 1.45 to 1.56.1

Here is a Sandcastle example of the Problem based on the 3D Models example:
[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=vVZtT9swEP4rVr80k4LzQhksFPbC2Is2NFbQPuWLm1wbC8eObKeUTfz3nRNSsiABU6cZCdnn587PPb5zumKarDhcgyZHRMI1OQHD65L+aGzeOGuWJ0paxiXosU9+pZLg4HKh3qk1SciCCQN+azUgILNcyc8y5xmzSg8BBcvVtUGr1fW9UdUifyt5ySzcbaXy9sVhKlcbfvGzCMb/nWEqF7VsIpJMA26fqRyEV2vhkwL4srD+XQYvOmbtkoK03HIwVEOpVvBWCK8N2GAw8UoZ3gQ+6rI+YdrijMldutCqfA9LDWC8nSjepeH+ZPIyeuWTyYSGe+HufviyY+DCdkELYDmXy/uYZ8wW1KoZmpk0XrS714dX3GYFgsOeTSshBqaiGhTQp/aYc+c+Q7x3d67fRvSbIP2DlOYoCPsz30uNlBZKl4YWg4Dfa9RaS4R7nU6+o/GnhI3GNxhwqDnLc+/uOtyQrHT36m7t3rjRP9lMe7t9wkl/1cOUrhZwt3eSG7XmDw5r4BwrrC7P+RrEBf/pGEXxwRDE1g50kTHhAHGI4x5x205vN9K2eVvNsivITzs5Wl0Qc+vUCgJXTaSwtjJJECy5Leo5zVQZfCm0ksp81KqugqW4/LBzwcpKwE5T5SaYCzUPSmbwKoKYhgE2XAs7LeeQ55A7C10Ku3CnkHOt8hpblpxqjZ2XjmY1EimhWSbkg2bLEqk1TYhP0oJxATmxiiCXCueUkJN2RoRaJuR0Nvs2S0iYvEYlxmP8Z27wFtYEXMB0lMp+T45dgkkU79MQ/6LkIDxoGCPxhiK+HXsoJg03HXu4ZYC4rcZ/o2/0pL4PuQqFZVIoYzdco8eS3TLE1un2Kql9Ac64uLrUdXY1yHqw+3wFBo7xlmo8N9xTyvytOngLl7C2tUYtHtRDt/NXddE5xdvXx5OhGjVG/mhq7I2A4/alesPLSmnrnkWP0sACpo5HYQ+gsGBpZoxzmwad0zTnK8Lzo3Q0+BGQjvCL7UC41X4Ak0kYVut0dDwN0Okx3xidn+0rVPNN+rYCLdiNgxTR8dfWSCmdBrh86GWVEnOmexF/Aw)

**Comment by hpinkos** [comment]
Thanks @gunmiosb, this is a known issue #7688
I'll tag you in that issue so we can notify you when it's fixed.  If it's not fixed in the May release, it should be fixed for June.
