### ISSUE TITLE
Rendering exception: geometry of undefined

### ISSUE THREAD

**Issue by heinerlamprecht** [AnalyticalGraphicsInc/cesium#7821]
I frequently get the following exception when loading a page with a Cesium viewport:

An error occurred while rendering. Rendering has stopped.
TypeError: Cannot set property 'geometry' of undefined
TypeError: Cannot set property 'geometry' of undefined
    at Object.M.unpackCombineGeometryParameters (http://localhost:8080/repos/devel/ng-web/master/assets/cesium/Workers/combineGeometry.js:231:19895)
    at r (http://localhost:8080/repos/devel/ng-web/master/assets/cesium/Workers/combineGeometry.js:231:21981)
    at i (http://localhost:8080/repos/devel/ng-web/master/assets/cesium/Workers/combineGeometry.js:231:21277)
    at http://localhost:8080/repos/devel/ng-web/master/assets/cesium/Workers/combineGeometry.js:231:21418

It happens both with Cesium 1.56.1 and 1.57.0.  Haven't checked any older versions.

Browser:
Chrome v73

Operating System:
macOS Mojave

**Comment by hpinkos** [comment]
@heinerlamprecht can you please provide some sample code to reproduce the error in [Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/)?  Thanks!

**Comment by mramato** [comment]
Feel free to re-open this with a reproducible example; there's no action we can take here without.
