### ISSUE TITLE
Fragment shader failed to compile.  too many uniforms

### ISSUE THREAD

**Issue by KleggerKoder** [AnalyticalGraphicsInc/cesium#7823]
Tested on iOS 12.2 devices I seem to get this error consistently after adding multiple imagery providers with defined rectangles, then  when zooming in beyond level 11. with 2 or more imagery provider rectangles within the visible range and terrain provider added to the viewer I receive this error: 
"RuntimeError: Fragment shader failed to compile.  Compile log: ERROR: too many uniforms"

I can never reproduce the error when I only have one imagery provider added to the viewer.

**Comment by OmarShehata** [comment]
Thanks for reporting this @KleggerKoder ! Are you able to provide a Sandcastle example that reproduces this crash for you? The Imagery Layers might be a good base to use:

https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/?src=Imagery%20Layers%20Manipulation.html

Does that crash for you? If not, perhaps try adding a few more layers and let us know if you can recreate it.

**Comment by KleggerKoder** [comment]
I have recreated the circumstances causing the crash on my development server.  
Please use this link to reproduce the crash.
The starting view causes a crash on an iPad Pro (12.9-inch) (2nd-generation) running iOS 12.2

[https://dev.air-suite.com/phantomworks/test.html](url)

**Comment by OmarShehata** [comment]
Thank you for the test case @KleggerKoder. I am able to see the same crash on the iPad in our office. I've put it in [a Sandcastle here](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=tVZ/b+I4EP0qFv/AStRJCIGQstXttZUOqd1WXXalk5BWJhmCdY7D2Q6FVv3uNwkhCT9u1at0lSrwzNjz/N7MGLJminxjBoTgBn5OHslnIuGZXIPmWUK/KzGFZCUwYJKwGNT2UaVrHoHqvM4kKf4yJUhA2ktjVjqwrAjWlHF1oTM8kIZpYt3c3lt1ioc1qDWHZ+v15c163eD/9o2uZNzu7g9M2IYnWXIHaxAB8Xfmt0+XM5l/zQFzyQ1n4jHV+JlKxFyh2QTkwhmNPMcZUdse2G7Pd3v96uwtul136Ax8lzqeOxza/WHtfQmI13MHI89Dp90buN6gV6a/PMr9oDhIw47TE7IEFnEZB6RHEYfv+EPb6TtenqtbR624CZc5VOoN7aHtu57bRyS9kdsIUqlAAuwawUzmCK6ZMigPky5mLoWqbQ2arrlS6c/pkaa7jykoxbj8gJzlTusPHi+fQNe6Kfg7A21+AELZfE1VwoQOiFEZVCGhgogbPL6dWw40zWsC1CHUH4Wt0w6L5XWKhHMJqt2tCeeHZYnQm9VcJTaH1w0qbqqIOdNwx7agHnn4Vx6xQPhwfMDthsWYb6d7QJzKzyQiya3HG5dpAr9nxpx6YkjDNDpNpUOQcI+ef0HCExBIw9lt7s2DFNsj1tfqPIBFJoRGSUCe9+tlmonoS3EzIKdeFqXPmhwlK6vgCSReLb9FGbBT+kByVMqxv//vEwdzvHfYOG7jHqFhMhbIcwPe097auSj623G6xKY+Nrfndwna7FG/n5tGw6Hr9z81hlehRFHQtCzaotw0ZVHUaaSYNJydHUVY7yTBwZNUfVviHeHRe0ZrTp0PcPrfWXV+weoveH0Xs3sWK2IdOvJHA/+E2Qa3H2TXeQ+7dc0WXYb0lrmKZfU2hCzB2VB7d+tSn92CLlSmDQJZpGsMtOnAsf2Bd0ksy/VIBDG2o8ZHhih8RpjUZ3ZKYPmcdKi976UGljIn1WDy6VkLHGFTclmOqKMHtBInrV+14MxLV8Vhc08VolvglA/21N4zo/imTyc3t1+nk+mfVb+XswmvHFOQbC4gQvzFNGl4Y5HOofTf4duCaONG2HFgBCuznOKlvsSomDaldLgjnzaXrW5rrM1WwNUO8288WaXK5FXeodQyZT9oa57hkDU01DqHOrb2m8YRXxMefZ61jl6fWYuEgmmNnnyAfuMvMGtdjS2MP9gm0uKHQP57R7BtHrJ0ru52Rkrp2MLl6S6TpmLOVOPEfwA). Hopefully we'll get a chance to look into this soon.

Thanks again for reporting this.

**Comment by KleggerKoder** [comment]
Great to hear.  Thanks for the quick reply.

**Comment by KleggerKoder** [comment]
Just to update I have tested again on the most recent build and am still seeing this issue.  
Unfortunately this is a deal breaker for using cesium in our product as we need to use multiple image providers to use cesium offline.

**Comment by KleggerKoder** [comment]
Updated to cesium 1.62 and tested on iOS 13.1.2 and this is still an issue.  @OmarShehata any updates?

**Comment by dzungpng** [comment]
Similar issue with the vertex shader on the iPhone: https://community.cesium.com/t/gltf-glb-limitation/.

**Comment by iLoveBug** [comment]
I meet the similar issue on my iPad mini2 running iOS 12.5.2, iPhone 7 Plus with iOS 13, when I try to load a GLTF model, I got the following error:

RuntimeError: Vertex shader failed to compile.  Compile log: ERROR: too many uniforms

RuntimeError@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:6835:22
createAndLinkProgram@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:104540:31
reinitialize@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:104772:39
initialize$7@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:104765:17
_bind@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:104841:17
beginDraw@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:223631:24
draw@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:223737:14
execute@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:100572:17
executeCommand@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:281195:61
executeCommands@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:281667:23
executeCommandsInViewport@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:282223:20
updateAndExecuteCommands@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:281951:32
render@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:282835:35
tryAndCatchError@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:282854:24
render@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:282944:23
render@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:297512:25
render@https://cesium.com/downloads/cesiumjs/releases/1.81/Build/CesiumUnminified/Cesium.js:296767:26

I have limit the GLTF model for vertex associated with bones to 2, that means at most 2 bones will influence a vertex. I found some document to indicate the number is 4.

Is there any other limitation?

**Comment by LegendTian** [comment]
mac book pro上也有类似问题：
RuntimeError: Fragment shader failed to compile.  Compile log: 
Error
    at new RuntimeError (http://127.0.0.1:5500/Cesium/Cesium.js:3960:19)
    at createAndLinkProgram (http://127.0.0.1:5500/Cesium/Cesium.js:93545:23)
    at initialize (http://127.0.0.1:5500/Cesium/Cesium.js:93766:23)
    at ShaderProgram._bind (http://127.0.0.1:5500/Cesium/Cesium.js:93783:9)
    at beginDraw (http://127.0.0.1:5500/Cesium/Cesium.js:168962:23)
    at Context.draw (http://127.0.0.1:5500/Cesium/Cesium.js:169024:9)
    at DrawCommand.execute (http://127.0.0.1:5500/Cesium/Cesium.js:89729:17)
    at ComputeEngine.execute (http://127.0.0.1:5500/Cesium/Cesium.js:166223:21)
    at ComputeCommand.execute (http://127.0.0.1:5500/Cesium/Cesium.js:166091:23)
    at executeComputeCommands (http://127.0.0.1:5500/Cesium/Cesium.js:234332:31)

我是在用primitives记载大量wallgeometry时遇到的。请问这个问题该怎么解决？
