### ISSUE TITLE
Explain why custom style expressions don't work with Point Clouds

### ISSUE THREAD

**Issue by OmarShehata** [AnalyticalGraphicsInc/cesium#7853]
I was trying to get a point cloud to have a custom expression, and I copied the following snippet directly [from the doc](https://cesiumjs.org/Cesium/Build/Documentation/Cesium3DTileStyle.html#show):

```
var style = new Cesium.Cesium3DTileStyle();
// Override show expression with a custom function
style.show = {
    evaluate : function(feature) {
        return true;
    }
};
```

But to my dismay, it crashes!

```
TypeError: this.show.getShaderFunction is not a function
TypeError: this.show.getShaderFunction is not a function
    at Cesium3DTileStyle.getShowShaderFunction (http://localhost:8080/Source/Scene/Cesium3DTileStyle.js:1603:67)
    at createShaders (http://localhost:8080/Source/Scene/PointCloud.js:934:39)
    at PointCloud.update (http://localhost:8080/Source/Scene/PointCloud.js:1384:13)
    at PointCloud3DTileContent.update (http://localhost:8080/Source/Scene/PointCloud3DTileContent.js:329:20)
    at Cesium3DTile.process (http://localhost:8080/Source/Scene/Cesium3DTile.js:1370:23)
    at processTiles (http://localhost:8080/Source/Scene/Cesium3DTileset.js:1890:22)
    at Cesium3DTileset.prePassesUpdate (http://localhost:8080/Source/Scene/Cesium3DTileset.js:1750:9)
    at PrimitiveCollection.prePassesUpdate (http://localhost:8080/Source/Scene/PrimitiveCollection.js:384:27)
    at prePassesUpdate (http://localhost:8080/Source/Scene/Scene.js:3205:20)
    at tryAndCatchError (http://localhost:8080/Source/Scene/Scene.js:3301:13)
```

[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html#c=pVYLb9s2EP4rnDfAMqBSsiXZzsPFXDduAyRIUKcthnooaImO2VGkQFJOvSL/fUe9bCVu0WKCHyJ5d7zv7uMdPQ9NBaJfSZpxivRGPjBxjwjKJBMGxVzmCTKMU03tiGjN1owmaLUDmTdUptSoXS2Al2JLFNoy+kAVmiBBH9CMapan+EMx53TjYjiTwhAmqOq66NtSIHgMVQqmbpXcsgS0T2vNWFFi6EepeHJXyji9pXjsnS3FUnjebeHnrPATnAL9NUa3FMyhKedUuGgmeZ6uGEHvBdtSpZnZoXdyJQ2LNboiK4wWMRHCwgYDU06/EJEoie6UjGPJGYIhugYfGJoxGRPFGa2Q1oFpQS3/gtd35aJTAcwVbzBdSvGOapmrmOK1kulUg+Bl4vSH4aBfoyvDiHVMBcWZYikz4L/GJEmcauM6CPtMFJsioiikNKOgRCHSvIBgNhStpUqJQUwjna++0NggI1G8IeKeIiZKkdzkygIEs3OpUCrBWEIhX1y7SFN6WizBszEm06eed8/MJl/hWKbeVBC+g8AS/kaRbAMRvhSxFyQvCoc9oyhtRi8E/Wo86/C88Ep7NYoyuDXbYmKYFHe/Guouxl7zmWaZ9hYFx18TQ7yWojdr7VRSqmCUVxP7i5ai65bWn/i1y2iT19mzJTy7WFy+v/4cvP58d3l18ROpPQq7TPTRJazNDk7ud+OysMt1ZIDP0p6talhOiYRZexrmP+3n7fNp2fnjG0se0WQyQV0l5brfXXZctOwUhpzu774fzudzOMY+jnrLzt/ujwwYCahfSWNk+tROELx6NRz+ip07mT135uRkOv1JIxbN4H+jCZ5YmM/H4yD4FQvhMwvT6WDwfQtdo3LabWvM576/19grVK+PTb205+qn+GLF4ZTfQMFUUI+LxmBLiqLAQCnQA5x56ABxriGZUDNEbCm0FIVxXEhPapbRLeE51E/gVy3orKGoQ5npHTJRUZiCIgT4zvaOw6t5wvTiv8RzeJBiklJFMEjablNTPqHaMFGcmNMWZqIMvBEROGHo90dhiIdh2A+joB+6aDCI/KiPw74/Gp/0+340cFEYnUThwMfBKByNwzAIelVupGK2zD7b4i0lCbSVW2bizTvJuRPBFsNREIz9yA9ORtHIRS98PBgNh/6oHwXj4GQ8HrpoiAfjPmw6HkWh7/vj6LDhoUtRVnGbBrKSuSnKdpwrBU7wHdqw+w2Hr4E2XYW5TPzhQpOcSuIU5SKha+jJyR7UPcSNzyzL2pEreNcrc1O4VMwAHSpjaEc5BwaAgxsJDMIHiYIOIBYZienFFtx9C42J23lofyLLzbRiR0UTsHAtc02vwYqTwo9tZw1nbCzWB7s+EI2AoFsGKu04uBadLOLUzJY22Bo5FawKvnOgh2uatnh6RACXhXXSWmtF8OyH+qDZxH/P/QbmLYv/AaA2B01G7ZLNagZrNJk3dtq9BRabwGEqklupi2LfO9vj/+1JAFoWe0eO6BEP39aYyjvEoZPH4bY2qQwe8gvD1VPQti9llN3vB7lGdUQLtmyZ/+vi6urmI7Z1bMqzDXFs8QT1R7eWWzzhatHOr2/eLy4+X998uLDCHbdzXhSjl+W+f7I0k8rYC4gDtw5D4cIBhU97qxwcMjjW2qqde7XSecK2iCUTKObti/GyU94zYGWdc75g/9Jl5+W5B/ItNS6LEmPrNCc7K7Lpv7wqJzHG5x4Ma63/AA).

@lilleyse mentioned it was because the Point Cloud shader backend doesn't support custom expressions like this. This limitation is alluded to [in the spec](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification/Styling#point-cloud). But it's weird as a user to try something directly out of the docs and get a non-meaningful error.

We could potentially support it by creating some kind of on-the-fly shader recompilation as the value changes, but for now we should at least mention something in the docs, or better yet, have the error that comes up explain this.

**Comment by andynines** [comment]
I don't see an error in the console when I view the Sandcastle example. Is this issue still current?
