### ISSUE TITLE
Cesium crashes when a tile contains no scene

### ISSUE THREAD

**Issue by abellgithub** [AnalyticalGraphicsInc/cesium#7946]
Sandcastle example: 

This glTF JSON throws an exception:

```
{
  "accessors": [
    {
      "bufferView": 0,
      "componentType": 5125,
      "count": 1581030,
      "type": "SCALAR"
    },
    {
      "bufferView": 1,
      "componentType": 5126,
      "count": 263503,
      "max": [
        -2505385.75,
        -3847596,
        4412408.5
      ],
      "min": [
        -2505738.25,
        -3847948.5,
        4412055.5
      ],
      "type": "VEC3"
    }
  ],
  "asset": {
    "version": "2.0"
  },
  "bufferViews": [
    {
      "buffer": 0,
      "byteLength": 6324120,
      "byteOffset": 0,
      "target": 34963
    },
    {
      "buffer": 0,
      "byteLength": 3162036,
      "byteOffset": 6324120,
      "target": 34962
    }
  ],
  "buffers": [
    {
      "byteLength": 9486156,
      "uri": "tile_1.bin"
    }
  ]
}
```

TypeError: Cannot read property 'undefined' of undefined
    at Object.ModelUtility.computeBoundingSphere (http://localhost:8080/Source/Scene/ModelUtility.js:206:36)
    at Model.update (http://localhost:8080/Source/Scene/Model.js:4699:57)
    at Batched3DModel3DTileContent.update (http://localhost:8080/Source/Scene/Batched3DModel3DTileContent.js:514:21)
    at Cesium3DTile.process (http://localhost:8080/Source/Scene/Cesium3DTile.js:1370:23)
    at processTiles (http://localhost:8080/Source/Scene/Cesium3DTileset.js:1882:22)
    at Cesium3DTileset.prePassesUpdate (http://localhost:8080/Source/Scene/Cesium3DTileset.js:1741:9)
    at PrimitiveCollection.prePassesUpdate (http://localhost:8080/Source/Scene/PrimitiveCollection.js:384:27)
    at prePassesUpdate (http://localhost:8080/Source/Scene/Scene.js:3205:20)
    at tryAndCatchError (http://localhost:8080/Source/Scene/Scene.js:3301:13)
    at Scene.render (http://localhost:8080/Source/Scene/Scene.js:3351:9)

I believe that it is because the tile contains no scenes, but the spec allows a glTF to contain no scenes.

Browser: N/A

Operating System: N/A

**Comment by abellgithub** [comment]
I'll add the more general suggesting that JSON in the various 3D tile formats should be schema checked before interpretation to avoid checks and provide feedback that would actually be helpful.

**Comment by OmarShehata** [comment]
Thanks for reporting this @abellgithub. Can you provide the `.bin` file that goes along with this, just to have a complete example to test here?

**Comment by hpinkos** [comment]
Closing due to inactivity.  @abellgithub if you're still having trouble feel free to reopen this issue
