### ISSUE TITLE
Error when HDR is turned off, log depth is disabled, and shadows are enabled

### ISSUE THREAD

**Issue by lilleyse** [AnalyticalGraphicsInc/cesium#8372]
In this [sandcastle](https://sandcastle.cesium.com/#c=hVTbbts4EP0V1i9WAJXW/ZI4wSLxAgnQdruJsYsCfmGkkUWEIg2ScpoW+feObo6TFLuCAWvImXNGcw65Z5rsOTyCJudEwiO5AsPbhv7Trznzog+vlLSMS9Bzl/zcSIKPBa1x6atWe15i9elUWWhgFv5VWpTrIcc5cYcaU7NSPRrMtbqFjXw+OdvIjeQVcT4MTVBTgARa8229epKs4cUtk1u4a3c7pS2UJxP9I5cIRZkAbZ35uuaG3GvExk5KBYZIZYkZqkiHRsoBjugOj8475ueO/BVvwRrQjBqw3fc7I1cJxnLJLFcSWz8a0hXDngxnMnQ++rkfe3lK0ywJ08jP4tglH6M0C8M4oVnsx2Gee5lLcDPLspRGYZQESRZOs1GaAw75Pck1sJLL7Vdui/pWCeEk1E8Sz4viKAuzLE4iJPKoF4VBFESen+JekuU5LuOqF/hpnid+Hsc5JqfRxAeyXOMsTKV08yLeZ2Y1/x7Rm9WfX9Y3628Hjf5THrROJ2ifeMdkWTBjBVBWlmu13Qq4bK1V0plfr27RQF2qS6pWFt3HOkUNxcORsv/HNOafvbSGFm61wK05pQv83bFmJ2DFLFs0qgRhFivNCnWlmp0GY6BcDF/7mYuHtW6LB7oVtpqfDVA7ZXivwvl7mWmlVXOLeuDgUHKax36CQw9SfEmDLOlGnoRBEOapl2dREORJ7hIfY1QCVfGjJPS9PD4ZuepB2xcqnH9NrXqhiKk3Je86B2CqN8YazXAU1rs3R/idcUY2d0Bye4AJ/Nh+h24OBjG0fgP2d4uHXMtOwGlgbtfChGcKPJqI5KMHDyohA7dPuDpq3MccTOeU6bCh1oB+REFHox70OD28/vbIHEXjfi8+7ozI3dNq/gq8v5X6Vk+H/2H5+fe+F2rLNLc1unEFO1tftlXVX5wVEwbOZu5saeyTgIsB5Q/e9PcP0jloSwtoS5yaWdyj58DSwpiOZLmYipYl3xNenm9mb67dzYwUghmDO1UrxB3/AZvZxXKB+a/KhOpV+msPWrCnLqX2Lz4Ni5TS5QLD91VWKXHP9BHiLw) uncheck HDR and you get an error

```
TypeError: Cannot read property 'execute' of undefined
    at executeCommand (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:239389:64)
    at executeCommands (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:239756:21)
    at executeCommandsInViewport (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:240177:13)
    at Scene.updateAndExecuteCommands (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:239970:17)
    at render (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:240633:19)
    at tryAndCatchError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:240652:17)
    at Scene.render (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:240727:17)
    at CesiumWidget.render (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:253442:29)
    at render (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:252779:36)
```

The error does not happen if HDR is disabled initially, or even when HDR is disabled initially, then enabled, then disabled. The error is related to derived commands and has existed as far back as HDR was introduced in 1.52.

**Comment by lilleyse** [comment]
Came up again in https://github.com/CesiumGS/cesium/issues/9031

**Comment by jjhembd** [comment]
Here is an [updated Sandcastle](https://sandcastle.cesium.com/#c=hVTbbts4EP0Vrl+sACqt+8Vxg0XjBRqg18TYYgG/MNLIIkKRBkklzS7y7x1KvjUutoABa4bDc4ZzDvnINHnk8ASavCUSnsg1GN539O8h502rIbxW0jIuQU998t9aEmJBa0zM9+WrMaaNVt03pUW9S3gXvis3LavVkyFzYnUPa/lycbmWa8kb4v0xslNTgQTa8k27fJas49Utkxu467dbpS3UFyPvE5cIRJkAbb3pquWG3GtExvZrBYZIZYkZ9xCHReoRjGiHRqeO98VR/8RasQ40owasO7Y3MNVgLJfMcoWnPBnMNcN2DGcy9t6EZZgGZU7zIovzJCzS1CdvkryI4zSjRRqmcVkGhU9wsSiKnCZxkkVZEY9DUZoDjvWM4T2wmsvNF26r9lYJ4WU0zLIgSNKkiIsizRJkCWiQxFESJUGY41pWlCWmMRtEYV6WWVimaYnFeTKSgaxXOAPTKN0dVPvIrObfE3qz/OvT6mb1z0GY/9UEjeJUHArvmKwrZqwAyup6pTYbAe96a5X0pu+Xt2gXV+qTppeVO6hXtVA9HOQk5HdMu/rLY2to2F4LXJpSOsPfHeu2ApbMslmnahBmttSsUteq22owBurZeNqPXDysdF890I2wzfRyhNoqw11jiHcm8ODmWxQD54Zi0zINM5x4lONHHhWZm3cWR1Fc5kFZJFFUZqVPQoxRBpQkTLI4DMr0YsfVjsIeqXD+LbXqSJHSYF+8dfJjabCLNTrhJGy3ry7smWt2bP6I5A8Ae/AT6x27OfjD0PYV2Nee4Y2XTsD9wHzXwh7PVHgjESlEAx5UQgZunzG703iIORjnlPGOodIwd2oOFt0jzw9f59fkJBgWB8XnezP1mh/hyNjVfPwbUi/+rx0u1IZpblv03RK2tn3XN83wIDZMGLic+JOFsc8CrkbcP3k3PDDI5KEBLaABcT5mdo/uAksrYxzJYrbftKj5I+H12/Xk1XO6npBKMGNwpemFuOP/wnpytZhh/U/bhBr0+PwIWrBnV9KGVx/GJKV0McPwfJdVStwzfYL4Aw) that works in 1.124. The bug is still there.
