### ISSUE TITLE
Test Failure - Scene/Primitive shader validation

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#8573]
I'm seeing this in master on Chrome.  @lilleyse @IanLilleyT, do you see this too?

```
Scene/Primitive shader validation
Expected function to throw DeveloperError.
Error: Expected function to throw DeveloperError.
    at stack (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1475:17)
    at buildExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1445:14)
    at Spec.expectationResultFactory (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:584:18)
    at Spec.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:332:34)
    at Expectation.addExpectationResult (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:528:21)
    at Expectation.toThrowDeveloperError (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1399:12)
    at http://localhost:8080/Specs/Scene/PrimitiveSpec.js:1175:12
    at Object.<anonymous> (http://localhost:8080/Specs/spec-main.js:89:30)
    at attemptAsync (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1793:24)
    at QueueRunner.run (http://localhost:8080/ThirdParty/jasmine-2.2.0/jasmine.js:1746:26)
```

**Comment by lilleyse** [comment]
I see this on Linux but not Windows

**Comment by OmarShehata** [comment]
I can see this in the 1.75 release, also on Linux but not on Windows. It's the only test failure at the time of writing.
