### ISSUE TITLE
Test failures - Scene/PointPrimitiveCollection 

### ISSUE THREAD

**Issue by hpinkos** [AnalyticalGraphicsInc/cesium#8574]
I'm seeing these test failures in master in Chrome.  @lilleyse @IanLilleyT do you see these failures?

```
Scene/PointPrimitiveCollection picks a pointPrimitive using scaleByDistance
Expected to pick undefined, but picked: [object Object]
   at http://localhost:8080/Specs/Scene/PointPrimitiveCollectionSpec.js:714:23
```

```
Scene/PointPrimitiveCollection renders pointPrimitive with scaleByDistance
Expected to render [0,0,0,255], but actually rendered [0,255,0,255].
    at http://localhost:8080/Specs/Scene/PointPrimitiveCollectionSpec.js:201:23
```

**Comment by lilleyse** [comment]
I see this on Linux but not Windows
